# Check duplicates

In [2]:
import pandas as pd
import sqlite3
import datetime

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [3]:
with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    onehousing_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)
    cleaned = pd.read_sql('SELECT * FROM cleaned', conn)

In [21]:
print(f'Number of duplicated rows in bds_raw: {bds_raw.duplicated().sum()} / {bds_raw.shape[0]}')
print(f'Number of duplicated rows in onehousing_raw: {onehousing_raw.duplicated().sum()} / {onehousing_raw.shape[0]}')
print(f'Number of duplicated rows in cleaned: {cleaned.duplicated().sum()} / {cleaned.shape[0]}')

Number of duplicated rows in bds_raw: 0 / 124933
Number of duplicated rows in onehousing_raw: 694 / 5178
Number of duplicated rows in cleaned: 4 / 10682

## Onehousing_raw

In [130]:
onehousing_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5178 entries, 0 to 5177
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   property_id           5175 non-null   object
 1   property_url          5178 non-null   object
 2   listing_title         5176 non-null   object
 3   total_price           5174 non-null   object
 4   unit_price            5174 non-null   object
 5   city                  5145 non-null   object
 6   district              5145 non-null   object
 7   alley_width           3813 non-null   object
 8   features              5176 non-null   object
 9   latitude              5176 non-null   float64
 10  longitude             5176 non-null   float64
 11  property_description  4207 non-null   object
 12  image_url             5176 non-null   object
dtypes: float64(2), object(11)
memory usage: 526.0+ KB

### Check NaN

In [135]:
onehousing_raw[onehousing_raw['property_description'].isna()]

,property_id,property_url,listing_title,total_price,unit_price,city,district,alley_width,features,latitude,longitude,property_description,image_url
0,ULHEKO,https://onehousing.vn/bds/Nha-mat-ngo-cach-Pho-Lua-100m--P--Van-Phuc--Q--Ha-Dong--TP--Ha-Noi.ULHEKO,"Nhà mặt ngõ cách Phố Lụa 100m, P. Vạn Phúc, Q. Hà Đông, TP. Hà Nội",9.2 tỷ,271 triệu/m²,TP. Hà Nội,Q. Hà Đông,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Bắc - 7.8m; Số tầng: 5; Diện tích: 33.9 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/355c72a5-37b5-4b62-819a-f1f34e64d071/2c9427839a4a2959019b2c413fa75633_CLONE/LIVING_ROOM/scaled_1000040570_1765975397648.jpg
1,SKUOOI,https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Dinh-50m--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.SKUOOI,"Nhà mặt ngõ cách Xuân Đỉnh 50m, P. Xuân Đỉnh, Q. Bắc Từ Liêm, TP. Hà Nội",17 tỷ,422 triệu/m²,TP. Hà Nội,Q. Bắc Từ Liêm,Độ rộng ngõ\r\n4m - 6m,Hướng mặt tiền: Tây Bắc - 4.1m; Số tầng: 6; Diện tích: 40.3 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/eb81035f-a264-4aed-932c-e524bac4e5e5/2c9427839a4a2959019ba140fe0c7de0_CLONE/LIVING_ROOM/image_picker_0225B86C-1140-496C-9131-6DC827356E26-75883-00001587015572D0_1767937910623.jpg
2,YWGUVT,https://onehousing.vn/bds/Nha-mat-ngo-cach-Kim-Nguu-100m--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.YWGUVT,"Nhà mặt ngõ cách Kim Ngưu 100m, P. Vĩnh Tuy, Q. Hai Bà Trưng, TP. Hà Nội",5.2 tỷ,203 triệu/m²,TP. Hà Nội,Q. Hai Bà Trưng,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Đông Bắc - 1.2m; Số tầng: 4.5; Diện tích: 25.6 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/62ea34f7-62ce-4f11-92c8-cd8d8c9ca823/2c9427839a4a2959019b30c1bfac58c6_CLONE/LIVING_ROOM/scaled_1000060304_1766050118802.jpg
3,IIWMDZ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ha-Tri-20m--P--Ha-Cau--Q--Ha-Dong--TP--Ha-Noi.IIWMDZ,"Nhà mặt ngõ cách Hà Trì 20m, P. Hà Cầu, Q. Hà Đông, TP. Hà Nội",18.5 tỷ,242 triệu/m²,TP. Hà Nội,Q. Hà Đông,Độ rộng ngõ\r\n6m - 7m,Hướng mặt tiền: Đông Nam - 5m; Số tầng: 4; Diện tích: 76.5 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/8ebf97a2-39ac-491a-a797-aad2e820c127/2c9427839a4a2959019b48e5eb8d5f0c_CLONE/LIVING_ROOM/scaled_1000060911_1766455083168.jpg
4,NKHHRZ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Thai-Thinh-30m--P--Thinh-Quang--Q--Dong-Da--TP--Ha-Noi.NKHHRZ,"Nhà mặt ngõ cách Thái Thịnh 30m, P. Thịnh Quang, Q. Đống Đa, TP. Hà Nội",19.5 tỷ,548 triệu/m²,TP. Hà Nội,Q. Đống Đa,Độ rộng ngõ\r\n3m - 4m,Hướng mặt tiền: Tây Bắc - 3.4m; Số tầng: 6; Diện tích: 35.6 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/8995d755-c3d8-4b33-9b79-39c28c273d4f/2c9427839a4a2959019ba138a6847ddd_CLONE/LIVING_ROOM/image_picker_2E3A0736-3D43-4694-BD18-B10DAE346EF8-88338-00002DF9C82EA189_1767937353914.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,XZVFLI,https://onehousing.vn/bds/Nha-mat-ngo-cach-An-Duong-Vuong--duong-gom-chan-de--30m--P--Phu-Thuong--Q--Tay-Ho--TP--Ha-Noi.XZVFLI,"Nhà mặt ngõ cách An Dương Vương (đường gom chân đê) 30m, P. Phú Thượng, Q. Tây Hồ, TP. Hà Nội",7.3 tỷ,243 triệu/m²,TP. Hà Nội,Q. Tây Hồ,Độ rộng ngõ\n2m - 3m,Hướng mặt tiền: Đông - 3.37m; Số tầng: 5; Diện tích: 30 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/a9ed56bc-be04-41dd-b4ac-be616ecbef5b/2c94211a9a4a2a77019bc537c83311b0_CLONE/LIVING_ROOM/image_picker_92E6F958-8977-4334-8955-A0ED2616217D-12059-000003F8BE41603C_1768540949790.jpg
967,HEJKTD,https://onehousing.vn/bds/Dat-nen-cach-Thuy-Khue-30m--P--Thuy-Khue--Q--Tay-Ho--TP--Ha-Noi.HEJKTD,"Đất nền cách Thụy Khuê 30m, P. Thụy Khuê, Q. Tây Hồ, TP. Hà Nội",12.5 tỷ,298 triệu/m²,TP. Hà Nội,Q. Tây Hồ,Độ rộng ngõ\n4m - 6m,Hướng mặt tiền: Tây - 5m; Diện tích: 42 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/b8cefe55-d83a-4b16-8157-10d1da022c28/2c9427839a4a2959019bc52d6a970ed4_CLONE/LOCAL_STREET/image_picker_980BAC1D-452B-4E0E-89B6-93D72319DE8A-17715-00003D5AED13AD36_1768539992110.jpg
968,DFWKWE,https://onehousing.vn/bds/Nha-mat-pho-Ho-Dac-Di--P--Nam-Dong--Q--Dong-Da--TP--Ha-Noi.DFWKWE,"Nhà mặt phố Hồ Đắc Di, P. Nam Đồng, Q. Đống Đa, TP. Hà Nội",20 tỷ,523 triệu/m²,TP. Hà Nội,Q. Đống Đa,None,Hướng mặt tiền: Nam - 3.5m; Số tầng: 5; Diện tích: 38.26 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/cad56689-256f-4cb0-8e25-a5b92ec82f77/2c94211a9a4a2a77019bc50e48851197_CLONE/LOCAL_STREET/image_picker_124CD226-D867-4B9C-B020-650F4B8F7B41-28308-0000035C4C919F0A_1768539659522.jpg
4432,None,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None
5108,None,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None

### Check duplicates

In [24]:
onehousing_raw.duplicated(subset=['property_id', 'property_description', 'listing_title', 'total_price', 'unit_price', 'city', 'district', 'alley_width', 'features']).sum()

np.int64(694)

In [50]:
onehousing_raw[onehousing_raw.duplicated(keep=False)]['property_id'].value_counts()
# Cái này chỉ đếm các giá trị bị lặp và trừ cái giá trị đầu tiên ra cho nên nó mới có đoạn count = 1. Thêm keep=False sẽ loại bỏ trường hợp này

property_id
NUOM18    3
DRRYCF    3
SCIKUF    3
N6LXER    3
P0OH1K    3
         ..
SBYPWV    2
DDR6H5    2
O9PAHW    2
WTJNTL    2
FIQGXM    2
Name: count, Length: 683, dtype: int64

In [53]:
onehousing_raw[onehousing_raw['property_id'] == 'LB4VTG']['alley_width'].duplicated()

644     False
1010    False
Name: alley_width, dtype: bool

In [85]:
onehousing_raw[(onehousing_raw['property_id'].duplicated()) & (onehousing_raw.duplicated() == False)].head()

,property_id,property_url,listing_title,total_price,unit_price,city,district,alley_width,features,latitude,longitude,property_description,image_url
1010,LB4VTG,https://onehousing.vn/bds/Nha-mat-ngo-cach-Au-Co-100m--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.LB4VTG,"Nhà mặt ngõ cách Âu Cơ 100m, P. Nhật Tân, Q. Tây Hồ, TP. Hà Nội",13.5 tỷ,162 triệu/m²,TP. Hà Nội,Q. Tây Hồ,Độ rộng ngõ\n3.1m - 3.9m,Hướng mặt tiền: Đông Nam - 5.3m; Số tầng: 7; Diện tích: 83.2 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Âu Cơ 100m, Q. Tây Hồ, diện tích 83.2m² x 7 tầng Nhà mặt tiền 5.3m, hướng Đông Nam, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 83.2m² với tổng diện tích xây dựng 400m²... Nhà mặt tiền 5.3m, hướng Đông Nam, độ rộng ngõ tiếp giáp 5m, khoảng cách ra trục đường chính 100m... Kết cấu bao gồm: 7 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/39ab8a42-617f-4742-be7f-2059bfe29e87/2c94211a9a4a2a77019b509fc21f67d8_CLONE/LIVING_ROOM/scaled_1000074668_1766584571308.jpg
1021,VK8IVO,https://onehousing.vn/bds/Nha-mat-ngo-cach-Phu-My-50m--P--My-Dinh-2--Q--Nam-Tu-Liem--TP--Ha-Noi.VK8IVO,"Nhà mặt ngõ cách Phú Mỹ 50m, P. Mỹ Đình 2, Q. Nam Từ Liêm, TP. Hà Nội",26 tỷ,371 triệu/m²,TP. Hà Nội,Q. Nam Từ Liêm,Độ rộng ngõ\n3.1m - 3.9m,Hướng mặt tiền: Đông - 4.66m; Số tầng: 7; Diện tích: 70 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Phú Mỹ 50m, Q. Nam Từ Liêm, diện tích 70m² x 7 tầng Nhà mặt tiền 4.66m, hướng Đông, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 70m² với tổng diện tích xây dựng 490m²... Nhà mặt tiền 4.66m, hướng Đông, độ rộng ngõ tiếp giáp 3m, khoảng cách ra trục đường chính 50m... Kết cấu bao gồm: 7 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/915545b2-a36d-406a-b8b7-9b59eb8907f3/2c9427839a4a2959019b5a1489bb6934_CLONE/LIVING_ROOM/image_picker_110454A4-6C77-4400-806D-2429FD12A82C-70572-000025D13C91E7B8_1766743697600.jpg
1046,6JEZ9M,https://onehousing.vn/bds/Nha-mat-ngo-cach-Bach-Mai-200m--P--Bach-Mai--Q--Hai-Ba-Trung--TP--Ha-Noi.6JEZ9M,"Nhà mặt ngõ cách Bạch Mai 200m, P. Bạch Mai, Q. Hai Bà Trưng, TP. Hà Nội",6.9 tỷ,325 triệu/m²,TP. Hà Nội,Q. Hai Bà Trưng,Độ rộng ngõ\n2m - 3m,Hướng mặt tiền: Nam - 3.33m; Số tầng: 5; Diện tích: 21.2 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Bạch Mai 200m, Q. Hai Bà Trưng, diện tích 21.2m² x 5 tầng Nhà mặt tiền 3.33m, hướng Nam, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 21.2m² với tổng diện tích xây dựng 100m²... Nhà mặt tiền 3.33m, hướng Nam, độ rộng ngõ tiếp giáp 2m, khoảng cách ra trục đường chính 200m... Kết cấu bao gồm: 5 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/11c1b8cf-7688-4867-b487-eb4b940f3382/2c9427839a4a2959019bd01c292e1191_CLONE/LIVING_ROOM/scaled_5091_1769255975213.jpg
1047,2EMHLG,https://onehousing.vn/bds/Nha-mat-ngo-cach-Lac-Long-Quan-50m--P--Nghia-Do--Q--Cau-Giay--TP--Ha-Noi.2EMHLG,"Nhà mặt ngõ cách Lạc Long Quân 50m, P. Nghĩa Đô, Q. Cầu Giấy, TP. Hà Nội",10 tỷ,333 triệu/m²,TP. Hà Nội,Q. Cầu Giấy,Độ rộng ngõ\n3.1m - 3.9m,Hướng mặt tiền: Tây Bắc - 3.42m; Số tầng: 5; Diện tích: 30 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Lạc Long Quân 50m, Q. Cầu Giấy, diện tích 30m² x 5 tầng Nhà mặt tiền 3.42m, hướng Tây Bắc, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 30m² với tổng diện tích xây dựng 150m²... Nhà mặt tiền 3.42m, hướng Tây Bắc, độ rộng ngõ tiếp giáp 3.5m, khoảng cách ra trục đường chính 50m... Kết cấu bao gồm: 5 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/2009aed9-9e79-4887-a5f3-87ac325093e4/2c9427839a4a2959019b5501facf669a_CLONE/LIVING_ROOM/image_picker_27679C95-6D43-462F-84A6-310409FAFAC3-34021-000009D49534E424_1766657988093.jpg
1054,OPP5GA,https://onehousing.vn/bds/Nha-mat-ngo-cach-Den-Lu-2-15m--P--Hoang-Van-Thu--Q--Hoang-Mai--TP--Ha-Noi.OPP5GA,"Nhà mặt ngõ cách Đền Lừ 2 15m, P. Hoàng Văn Thụ, Q. Hoàng Mai, TP. Hà Nội",33.5 tỷ,558 triệu/m²,TP. Hà Nội,Q. Hoàng Mai,Độ rộng ngõ\n6.1m - 10m,Hướng mặt tiền: Đông Nam - 4.38m; Số tầng: 7; Diện tích: 60 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Đền Lừ 2 15m, Q. Hoàng Mai, diện tích 60m² x 7 tầng Nhà mặt tiền 4.38m, hướng Đông Nam, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 60m² với tổng diện tích xây dựng 420m²... Nhà mặt tiền 4.38m, hướng Đông Nam, độ rộng ngõ tiếp giáp 12m, khoảng cách ra trục đường chính 15m... Kết cấu bao gồm: 7 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/f0bb84ef-e35e-43f4-8cf9-03e5ce2475cd/2c94211a9a4a2a77019bb600d2170a15_CLONE/LIVING_ROOM/image_picker_37346F50-8CFE-4BA8-B3F0-D9986F7DB9CF-339-0000001D846FCAFE_1768285990485.jpg

In [72]:
oh_raw_copy = onehousing_raw.copy()

null_ind = oh_raw_copy[oh_raw_copy['property_id'].isna()]['property_id'].index
extracted_ids = oh_raw_copy['property_url'].str.split('.').str[-1]
oh_raw_copy['property_id'] = oh_raw_copy['property_id'].fillna(extracted_ids)
oh_raw_copy.iloc[null_ind]

,property_id,property_url,listing_title,total_price,unit_price,city,district,alley_width,features,latitude,longitude,property_description,image_url
4432,YNZR7P,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None
5108,YNZR7P,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None
5160,LXJ7OH,https://onehousing.vn/bds/Nha-mat-ngo-cach-Quoc-Tu-Giam-200m--P--Quoc-Tu-Giam--Q--Dong-Da--TP--Ha-Noi.LXJ7OH,"Nhà mặt ngõ cách Quốc Tử Giám 200m, P. Quốc Tử Giám, Q. Đống Đa, TP. Hà Nội",8.4 tỷ,274 triệu/m²,TP. Hà Nội,Q. Đống Đa,Độ rộng ngõ\n2m - 3m,Hướng mặt tiền: Đông Bắc - 2.41m; Số tầng: 5; Diện tích: 30.7 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Quốc Tử Giám 200m, Q. Đống Đa, diện tích 30.7m² x 5 tầng Nhà mặt tiền 2.41m, hướng Đông Bắc, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 30.7m² với tổng diện tích xây dựng 30.7m²... Nhà mặt tiền 2.41m, hướng Đông Bắc, độ rộng ngõ tiếp giáp 3m, khoảng cách ra trục đường chính 200m... Kết cấu bao gồm: 5 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/d28b3d7d-f0c9-4c9b-a54c-e5261175c9c7/2c9427839a4a2959019c0eac56692716_CLONE/LOCAL_STREET/scaled_IMG20260129180635_1769773092015.jpg

In [80]:
oh_raw = onehousing_raw.copy()

extracted_city = oh_raw['listing_title'].str.split(',').str[-1]
extracted_district = oh_raw['listing_title'].str.split(',').str[-2]
oh_raw['new_city'] = oh_raw['city'].fillna(extracted_city)
oh_raw['new_district'] = oh_raw['district'].fillna(extracted_district)

oh_raw[(oh_raw['city'].isna()) | oh_raw['district'].isna()][['new_city', 'new_district', 'city', 'district', 'listing_title']]

,new_city,new_district,city,district,listing_title
1012,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Phúc Lợi 120m, P. Phúc Lợi, Q. Long Biên, TP. Hà Nội"
1013,TP. Hà Nội,Q. Bắc Từ Liêm,None,None,"Nhà mặt ngõ cách Trần Cung 300m, P. Cổ Nhuế 1, Q. Bắc Từ Liêm, TP. Hà Nội"
1020,TP. Hà Nội,Q. Ba Đình,None,None,"Nhà mặt ngõ cách Kim Mã 60m, P. Ngọc Khánh, Q. Ba Đình, TP. Hà Nội"
1023,TP. Hà Nội,Q. Hà Đông,None,None,"Nhà mặt ngõ cách Lê Trọng Tấn 30m, P. Dương Nội, Q. Hà Đông, TP. Hà Nội"
1872,TP. Hà Nội,Q. Nam Từ Liêm,None,None,"Nhà mặt ngõ cách Lương Thế Vinh 60m, P. Trung Văn, Q. Nam Từ Liêm, TP. Hà Nội"
1936,TP. Hà Nội,Q. Thanh Xuân,None,None,"Nhà mặt ngõ cách Bùi Xương Trạch 250m, P. Khương Đình, Q. Thanh Xuân, TP. Hà Nội"
1940,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Bờ Sông Sét 10m, P. Thịnh Liệt, Q. Hoàng Mai, TP. Hà Nội"
2379,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Trịnh Đình Cửu 20m, P. Định Công, Q. Hoàng Mai, TP. Hà Nội"
2791,TP. Hà Nội,Q. Ba Đình,None,None,"Nhà mặt ngõ cách Hoàng Hoa Thám 100m, P. Ngọc Hà, Q. Ba Đình, TP. Hà Nội"
3200,TP. Hà Nội,H. Gia Lâm,None,None,"Nhà mặt ngõ cách Đường Bát Khối 50m, X. Đông Dư, H. Gia Lâm, TP. Hà Nội"
4041,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Nguyễn Lam 100m, P. Phúc Đồng, Q. Long Biên, TP. Hà Nội"
4051,TP. Hà Nội,Q. Hai Bà Trưng,None,None,"Nhà mặt ngõ cách Đồng Nhân 40m, P. Đồng Nhân, Q. Hai Bà Trưng, TP. Hà Nội"
4055,TP. Hà Nội,Q. Nam Từ Liêm,None,None,"Nhà mặt ngõ cách Nguyễn Đổng Chi 30m, P. Cầu Diễn, Q. Nam Từ Liêm, TP. Hà Nội"
4432,None,None,None,None,None
4433,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Phúc Lợi 120m, P. Phúc Lợi, Q. Long Biên, TP. Hà Nội"
4434,TP. Hà Nội,Q. Bắc Từ Liêm,None,None,"Nhà mặt ngõ cách Trần Cung 300m, P. Cổ Nhuế 1, Q. Bắc Từ Liêm, TP. Hà Nội"
4435,TP. Hà Nội,Q. Ba Đình,None,None,"Nhà mặt ngõ cách Kim Mã 60m, P. Ngọc Khánh, Q. Ba Đình, TP. Hà Nội"
4436,TP. Hà Nội,Q. Hà Đông,None,None,"Nhà mặt ngõ cách Lê Trọng Tấn 30m, P. Dương Nội, Q. Hà Đông, TP. Hà Nội"
4588,TP. Hà Nội,Q. Nam Từ Liêm,None,None,"Nhà mặt ngõ cách Lương Thế Vinh 60m, P. Trung Văn, Q. Nam Từ Liêm, TP. Hà Nội"
4605,TP. Hà Nội,Q. Thanh Xuân,None,None,"Nhà mặt ngõ cách Bùi Xương Trạch 250m, P. Khương Đình, Q. Thanh Xuân, TP. Hà Nội"
4607,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Bờ Sông Sét 10m, P. Thịnh Liệt, Q. Hoàng Mai, TP. Hà Nội"
4678,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Trịnh Đình Cửu 20m, P. Định Công, Q. Hoàng Mai, TP. Hà Nội"
4762,TP. Hà Nội,Q. Ba Đình,None,None,"Nhà mặt ngõ cách Hoàng Hoa Thám 100m, P. Ngọc Hà, Q. Ba Đình, TP. Hà Nội"
4858,TP. Hà Nội,H. Gia Lâm,None,None,"Nhà mặt ngõ cách Đường Bát Khối 50m, X. Đông Dư, H. Gia Lâm, TP. Hà Nội"
5031,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Nguyễn Lam 100m, P. Phúc Đồng, Q. Long Biên, TP. Hà Nội"
5033,TP. Hà Nội,Q. Hai Bà Trưng,None,None,"Nhà mặt ngõ cách Đồng Nhân 40m, P. Đồng Nhân, Q. Hai Bà Trưng, TP. Hà Nội"
5034,TP. Hà Nội,Q. Nam Từ Liêm,None,None,"Nhà mặt ngõ cách Nguyễn Đổng Chi 30m, P. Cầu Diễn, Q. Nam Từ Liêm, TP. Hà Nội"
5108,None,None,None,None,None
5117,TP. Hà Nội,Q. Hà Đông,None,None,"Nhà mặt ngõ cách Đường Đa Sỹ 68m, P. Kiến Hưng, Q. Hà Đông, TP. Hà Nội"
5129,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Ngọc Trì 30m, P. Long Biên, Q. Long Biên, TP. Hà Nội"
5133,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Thịnh Liệt 10m, P. Thịnh Liệt, Q. Hoàng Mai, TP. Hà Nội"
5135,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Ngọc Trì 30m, P. Long Biên, Q. Long Biên, TP. Hà Nội"
5137,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Thịnh Liệt 10m, P. Thịnh Liệt, Q. Hoàng Mai, TP. Hà Nội"

In [94]:
oh_raw_copy = onehousing_raw.copy()

def new_oh_rule(oh_raw):
    # Bỏ các cột mà đến cả property_url với listing_title cũng chẳng có
    oh_raw.dropna(subset=['property_url', 'listing_title'], inplace=True)

    # Thay thế các cột có \r\n thành \n
    for col in ['listing_title', 'city', 'district', 'alley_width', 'features', 'property_description']:
        oh_raw[col] = oh_raw[col].str.replace('\r\n', '\n').str.strip()
    
    # Xử lý các trường hợp property_id bị null
    extracted_ids = oh_raw['property_url'].str.split('.').str[-1]
    oh_raw['property_id'] = oh_raw['property_id'].fillna(extracted_ids)

    # Xử lý các đoạn bị null city, district
    extracted_city = oh_raw['listing_title'].str.split(',').str[-1]
    extracted_district = oh_raw['listing_title'].str.split(',').str[-2]
    oh_raw['city'] = oh_raw['city'].fillna(extracted_city)
    oh_raw['district'] = oh_raw['district'].fillna(extracted_district)

    # Dropna nếu dòng có nhiều giá trị NULL
    oh_raw.dropna(subset=['listing_title', 'total_price', 'city', 'district'], inplace=True)

    # Drop duplicates nếu có
    oh_raw.drop_duplicates(inplace=True)

    return oh_raw

oh_raw_copy = new_oh_rule(oh_raw_copy)

In [87]:
oh_raw_copy.duplicated().sum()

np.int64(0)

## Batdongsan_raw

In [136]:
bds_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124933 entries, 0 to 124932
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             124933 non-null  object
 1   url            124933 non-null  object
 2   title          124933 non-null  object
 3   short_address  124933 non-null  object
 4   address_parts  124933 non-null  object
 5   latitude       124933 non-null  float64
 6   longitude      124933 non-null  float64
 7   main_info      124933 non-null  object
 8   description    124933 non-null  object
 9   other_info     124933 non-null  object
 10  image_urls     124933 non-null  object
dtypes: float64(2), object(9)
memory usage: 10.5+ MB

## Cleaned

In [97]:
cleaned[cleaned['Web'] == "Onehousing"][['Đơn giá xây dựng', 'Chất lượng còn lại']]

      Đơn giá xây dựng  Chất lượng còn lại
6451         8221171.0                0.85
6452         8221171.0                0.85
6453         8221171.0                0.85
6454         8221171.0                0.85
6455         8221171.0                0.85
...                ...                 ...
8785         8221171.0                0.85
8786         8221171.0                0.85
8787         8221171.0                0.85
8788               NaN                 NaN
8789         8221171.0                0.85

[982 rows x 2 columns]

In [106]:
print(cleaned.iloc[8788][['Chất lượng còn lại', 'Đơn giá xây dựng']])
print(pd.isna(cleaned.iloc[8788]['Chất lượng còn lại']))
print(pd.isna(cleaned.iloc[8788]['Đơn giá xây dựng']))

Chất lượng còn lại    NaN
Đơn giá xây dựng      NaN
Name: 8788, dtype: object
True
True

In [128]:
cleaned[cleaned['Yếu tố khác'].isna()]['Web'].value_counts()

Web
Onehousing    982
Batdongsan      2
Name: count, dtype: int64

In [119]:
cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10682 entries, 0 to 10681
Data columns (total 32 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Tỉnh/Thành phố                        10682 non-null  object
 1   Thành phố/Quận/Huyện/Thị xã           10682 non-null  object
 2   Xã/Phường/Thị trấn                    10682 non-null  object
 3   Đường phố                             10682 non-null  object
 4   Chi tiết                              10682 non-null  object
 5   Nguồn thông tin                       10682 non-null  object
 6   Tình trạng giao dịch                  10682 non-null  object
 7   Thời điểm giao dịch/rao bán           10682 non-null  object
 8   Thông tin liên hệ                     0 non-null      object
 9   Giá rao bán/giao dịch                 10682 non-null  float64
 10  Giá ước tính                          10682 non-null  int64
 11  Loại đơn giá (đ/m2 hoặc đ/m ngang)    10682 non-null  object
 12  Đơn giá đất                           9700 non-null   float64
 13  Lợi thế kinh doanh                    9700 non-null   object
 14  Số tầng công trình                    10682 non-null  float64
 15  Tổng diện tích sàn                    10682 non-null  float64
 16  Đơn giá xây dựng                      10674 non-null  float64
 17  Năm xây dựng                          0 non-null      object
 18  Chất lượng còn lại                    10674 non-null  float64
 19  Diện tích đất (m2)                    10682 non-null  float64
 20  Kích thước mặt tiền (m)               10682 non-null  float64
 21  Kích thước chiều dài (m)              10682 non-null  float64
 22  Số mặt tiền tiếp giáp                 10682 non-null  int64
 23  Hình dạng                             10682 non-null  object
 24  Độ rộng ngõ/ngách nhỏ nhất (m)        10682 non-null  float64
 25  Khoảng cách tới trục đường chính (m)  10682 non-null  float64
 26  Mục đích sử dụng đất                  10682 non-null  object
 27  Yếu tố khác                           9698 non-null   object
 28  Tọa độ (vĩ độ)                        10682 non-null  float64
 29  Tọa độ (kinh độ)                      10682 non-null  float64
 30  Hình ảnh của bài đăng                 10682 non-null  object
 31  Web                                   10682 non-null  object
dtypes: float64(13), int64(2), object(17)
memory usage: 2.6+ MB

# Chạy lại database

In [3]:
import sqlite3
import pandas as pd
from commons.config import *
from main import clean

# # Xuất raw data từ db cũ ra
# with sqlite3.connect('output/real_estate.db') as conn:
#     bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
#     oh_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)

# # Xuất raw data ra file csv
# bds_raw.to_csv(DETAILS_CSV_PATH['Batdongsan'], encoding='utf-8-sig', index=False)
# oh_raw.to_csv(DETAILS_CSV_PATH['Onehousing'], encoding='utf-8-sig', index=False)

# Chạy lại add clean đồ
clean()

Adding raw Batdongsan data to the database at 2026-02-12 09:15:36.355009...
Finished adding raw data of Batdongsan at 2026-02-12 09:15:58.024035!
Adding raw Onehousing data to the database at 2026-02-12 09:15:58.024035...
Finished adding raw data of Onehousing at 2026-02-12 09:15:58.174668!
Cleaning Batdongsan data at 2026-02-12 09:15:58.174668...
Dropped 0 duplicated raw rows for Batdongsan.
Ground truth file not found.
Dropped 21889 duplicated rows for Batdongsan.
Dropped 94155 NaN rows for Batdongsan.
Final number of rows for Batdongsan: 11681
Finished cleaning Batdongsan data at 2026-02-12 09:27:59.084629!
Cleaning Onehousing data at 2026-02-12 09:27:59.086135...
[OneHousing] Data cleaning completed.
Dropped 0 duplicated rows for Onehousing.
Dropped 0 NaN rows for Onehousing.
Final number of rows for Onehousing: 4053
Finished cleaning Onehousing data at 2026-02-12 09:27:59.635496!
Finished adding data to the database at 2026-02-12 09:28:00.649144!

# Simulating logging in and extracting phone numbers

In [18]:
from seleniumbase import SB

with SB(uc=True, headed=True) as sb:
    sb.open("https://batdongsan.com.vn")

    # Click the "Đăng nhập" button
    sb.wait_for_element_visible("#kct_login", timeout=10)
    sb.click("#kct_login")

    # Wait for the login iframe to appear
    sb.wait_for_element_visible(
        'iframe[src="https://batdongsan.com.vn/sellernet/internal-sign-in"]',
        timeout=10
    )

    # Switch into the iframe
    sb.switch_to_frame(
        'iframe[src="https://batdongsan.com.vn/sellernet/internal-sign-in"]'
    )

    # Wait for the username input inside iframe
    sb.wait_for_element_visible('input[name="username"]', timeout=15)

    # Username
    sb.wait_for_element_visible('input[name="username"]', timeout=15)
    sb.clear('input[name="username"]')
    sb.type('input[name="username"]', '0328765904')

    # Password
    sb.wait_for_element_visible('input[name="password"]', timeout=15)
    sb.clear('input[name="password"]')
    sb.type('input[name="password"]', 'Vyatran123')

    sb.click("#signin-button")

    sb.sleep(5)

    sb.switch_to_default_content()

    sb.open("https://batdongsan.com.vn/ban-nha-rieng-duong-bui-quang-la-phuong-14-8-67/ban-dep-co-phong-ngu-duoi-tret-o-nghi-qua-suong-lh-ngay-pr45137889")
    sb.wait_for_element_visible("div.js__phone-event", timeout=10)
    sb.js_click("div.js__phone-event")

    sb.sleep(5)

    phone = sb.get_attribute("div.js__phone-event", "mobile")
    print("Phone:", phone)

    sb.open("https://batdongsan.com.vn/ban-nha-rieng-duong-bui-quang-la-phuong-14-8/-moi-gia-re-gan-san-bay-cho-sieu-thi-e-mart-noi-that-moi-dep-don-vao-o-ngay-pr45071323")
    sb.wait_for_element_visible("div.js__phone-event", timeout=10)
    sb.js_click("div.js__phone-event")

    sb.sleep(5)
    other_phone = sb.get_attribute("div.js__phone-event", "mobile")
    print("Phone:", other_phone)

    cookies = sb.get_cookies()
    print(cookies)

Phone: 0902 812 702
Phone: 0906 882 545
[{'domain': '.batdongsan.com.vn', 'expiry': 1804556067, 'httpOnly': False, 'name': 'ttcsid', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '1770860035987::QRu89jrEHJnk9cL8hDR9.1.1770860067153.0'}, {'domain': '.batdongsan.com.vn', 'expiry': 1805420065, 'httpOnly': False, 'name': 'ab.storage.sessionId.892f88ed-1831-42b9-becb-90a189ce90ad', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '%7B%22g%22%3A%220886773e-e75d-8a7d-c53f-2c118a6ab19d%22%2C%22e%22%3A1770861865225%2C%22c%22%3A1770860050685%2C%22l%22%3A1770860065225%7D'}, {'domain': '.batdongsan.com.vn', 'expiry': 1805420065, 'httpOnly': False, 'name': '_ga_HTS298453C', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'GS2.1.s1770860035$o1$g1$t1770860065$j30$l0$h0$dDGxomvukk-Tm1zdCgEd0GEWV62iBPWM2kg'}, {'domain': '.batdongsan.com.vn', 'expiry': 1770946462, 'httpOnly': False, 'name': '_clsk', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '1jmku6v%5E1770860062206%5E4%5E1%5Ev.clarity.ms%2Fcollect'}, {'domain': '.batdongsan.com.vn', 'expiry': 1805420050, 'httpOnly': False, 'name': 'ab.storage.deviceId.892f88ed-1831-42b9-becb-90a189ce90ad', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '%7B%22g%22%3A%224c109fd0-2395-aa8b-1ee4-e28f55d278cb%22%2C%22c%22%3A1770860035735%2C%22l%22%3A1770860050685%7D'}, {'domain': '.batdongsan.com.vn', 'expiry': 1802396065, 'httpOnly': False, 'name': 'ajs_anonymous_id', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'a745712f-c1fb-4090-928b-5ffc430271d9'}, {'domain': '.batdongsan.com.vn', 'expiry': 1802396065, 'httpOnly': False, 'name': 'ajs_user_id', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '4546453'}, {'domain': 'batdongsan.com.vn', 'httpOnly': False, 'name': 'USER_PRODUCT_SEARCH', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '38%7C41%7CSG%7C67%7C8947%7C4761%7C0%2C45071323'}, {'domain': '.batdongsan.com.vn', 'expiry': 1802396046, 'httpOnly': True, 'name': 'accessToken', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg5Mzg0OTU1MkNDRTExMUFDMjc5RjUyNDI3RUEwMUY5QzdDMzAxNTQiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJpVGhKVlN6T0VSckNlZlVrSi1vQi1jZkRBVlEifQ.eyJuYmYiOjE3NzA4NjAwNTMsImV4cCI6MTc3MDg2MzY1MywiaXNzIjoiaHR0cDovL2F1dGhlbnRpY2F0aW9uLmJkcy5sYyIsImF1ZCI6IkFwaUdhdGV3YXkiLCJjbGllbnRfaWQiOiIwM2QwZjkwNS0xMGM5LTRkMjEtOTBmNS0xMGI3OGUwYTk4OWMiLCJzdWIiOiI0NTQ2NDUzIiwiYXV0aF90aW1lIjoxNzcwODg1MjUzLCJpZHAiOiJsb2NhbCIsInByZWZlcnJlZF91c2VybmFtZSI6InZ5YW5oY2hheWRlYWRsaW5lQGdtYWlsLmNvbSIsImVtYWlsIjoidnlhbmhjaGF5ZGVhZGxpbmVAZ21haWwuY29tIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsIkFwaUdhdGV3YXkiLCJvZmZsaW5lX2FjY2VzcyJdLCJhbXIiOlsicHdkIl19.NZXuJCDILGUV-znc_rbBlBmmoYF8iNWwvNegQkY5tbk2Wdif_Oqjsg2wledAAoNU0wEfCPYODVNZSZl9JDPUSPd3f1jTulay7MW9UXdgejmK77Gyjs0xADtjSdW2PuRJq9f0DOWUw4bGb65iQFh5LgSiB1CQpyVeV0rlCCaqYizwDB_0lDLTcB1G4HLTIxAPnPoCJ11lHmfhs6jAL_VGrN6g-DHmEAZ-hN-Sf4Lnj_RMt9jozwp5qR6iAEGek307CL2pDUd8JlE6UjoPPOVEzKtUDiFlwOMT48OHGt664GdPi9sx5_0HBrXI3Cb_KtUwIFUfNsu4FPFXuYZRYI7aQw'}, {'domain': '.batdongsan.com.vn', 'expiry': 1802396046, 'httpOnly': False, 'name': 'c_u_id', 'path': '/', 'sameSite': 'Lax', 'secure': True, 'value': '4546453'}, {'domain': 'batdongsan.com.vn', 'expiry': 1773452046, 'httpOnly': False, 'name': 'userinfo', 'path': '/', 'sameSite': 'Lax', 'secure': True, 'value': 'vyanhchaydeadline@gmail.com'}, {'domain': 'batdongsan.com.vn', 'expiry': 1805420061, 'httpOnly': False, 'name': '__IP', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '251154443'}, {'domain': 'batdongsan.com.vn', 'expiry': 1802396065, 'httpOnly': False, 'name': 'con.unl.usr.id', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '%7B%22key%22%3A%22userId%22%2C%22value%22%3A%22a745712f-c1fb-4090-928b-5ffc430271d9%22%2C%22expireDate%22%3A%222027-02-12T08%3A34%3A32.7071083Z%22%7D'}, {'domain': 'batdongsan.com.vn', 'expiry': 1771464865, 'httpOnly': False, 'name': 'AWSALB', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'c4ULBky4r3nBzDTRJ246oFj5deCNaObiY9mTKm4bovURN/5mBcKw55hwk0beSVMTgq1wL/DaNyxjRfZhshIBUduLaJDXSl8KLWglibzEx75y6RHd2H/fyrua5jHw'}, {'domain': 'batdongsan.com.vn', 'expiry': 1805420061, 'httpOnly': False, 'name': '__tb', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '0'}, {'domain': '.batdongsan.com.vn', 'expiry': 1802396061, 'httpOnly': False, 'name': '_hjSessionUser_1708983', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'eyJpZCI6IjI0YjBjNDk0LTk0NTgtNTNhOC1iMDQ0LTgwMTkwMjBhYTFiOCIsImNyZWF0ZWQiOjE3NzA4NjAwMzU1MjcsImV4aXN0aW5nIjp0cnVlfQ=='}, {'domain': '.batdongsan.com.vn', 'expiry': 1778636064, 'httpOnly': False, 'name': '_fbp', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'fb.2.1770860039029.614431924109855474'}, {'domain': 'batdongsan.com.vn', 'expiry': 1805420036, 'httpOnly': False, 'name': '__R', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '1'}, {'domain': 'batdongsan.com.vn', 'expiry': 1771724061, 'httpOnly': False, 'name': '__uif', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '__uid%3A9170860035452062975%7C__ui%3A-1%7C__create%3A1770860043'}, {'domain': 'batdongsan.com.vn', 'expiry': 1773452061, 'httpOnly': False, 'name': '__su', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': '0'}, {'domain': '.batdongsan.com.vn', 'expiry': 1802396035, 'httpOnly': True, 'name': 'cf_clearance', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'Efpmv_lmvIK8zicOoiBaUwACTZdlnagOgt8TgxffIH0-1770860043-1.2.1.1-Xd_ViHgvbRWWSWkxZwu7XFf8p_gSn0CakcVM0zoj5Ge9sYGIBsz8AwlofiVH69NpNWANJubi4a87vPAXiCRKRd5XWI6sZ0MjFfMPE1XxvKJFnCcuOufBG0SLyk5JQH4EZ3Zj57ntjkSimXhK4aJNNXgjcXU9ccvd78z1HlQ7H5jEQdKskD4Ad4MhJ0tknYAYCxDfXcV8LnDh7x2y0RGs3tgbwSOEBfCC29KCyD72LHo'}, {'domain': 'batdongsan.com.vn', 'expiry': 1805420036, 'httpOnly': False, 'name': '__RC', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '4'}, {'domain': '.batdongsan.com.vn', 'expiry': 1802396036, 'httpOnly': False, 'name': '_clck', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '10s797x%5E2%5Eg3i%5E0%5E2234'}, {'domain': '.batdongsan.com.vn', 'expiry': 1804556061, 'httpOnly': False, 'name': '_ttp', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '01KH7QQFWGN6SZM3ZR6JK13YM5_.tt.2'}, {'domain': 'batdongsan.com.vn', 'expiry': 1773452061, 'httpOnly': False, 'name': '__iid', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': '6461'}, {'domain': '.batdongsan.com.vn', 'expiry': 1805420035, 'httpOnly': False, 'name': '_ga', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'GA1.1.500315377.1770860036'}, {'domain': 'batdongsan.com.vn', 'httpOnly': False, 'name': '_hjHasCachedUserAttributes', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'true'}, {'domain': 'batdongsan.com.vn', 'expiry': 1802396065, 'httpOnly': False, 'name': 'con.unl.cli.id', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '%7B%22key%22%3A%22clientId%22%2C%22value%22%3A%226629bdf7-57bb-45f5-bf36-264eddb93a8a%22%2C%22expireDate%22%3A%222027-02-12T08%3A34%3A32.7071314Z%22%7D'}, {'domain': 'batdongsan.com.vn', 'expiry': 1773452065, 'httpOnly': False, 'name': 'con.unl.lat', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '1770829200'}, {'domain': 'batdongsan.com.vn', 'expiry': 1802396046, 'httpOnly': True, 'name': 'BDS.UMS.Cookie', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'CfDJ8PBeT99_5YlIiVs8v3TddN2BOuT7K5nCZdpYr991EMzoKYHbrpB7xoITfB5cp5A_N_QHCcX8iBWayQvye5UlNuQ6aQLgFdYLUDdTbJkeeHuHRs9Q9rdsgAL4eqcqzQcwjru4qB_-3bupd0QRZlXYwERJTWD565LUSB0Uo5gzRqbhWmsx0rjqm8FRdvNu7taHvxVp03Xds0sTaWwS5zvBKteN3FXUCoplOpbNgH_IvgFhXpi_3l4Tk9049awgHY6jQmdZDOYLNXe1Z1ZEsc6PBNxZrxCtjosZyC-gsqMefUSxY9u2Tgo19Y0boc4gvx4-UHRH6BKXS1pofraF9et2LLSNUiEvtDHi5T0QB1hkrEaPsgVfxa6IULV26-yKTT4yt9Ca4lfx7BxN_3rdqqcLHvFB1AM7m-HfdWdlS5PtSMoVQStgbelPl3VDudlqshW2Xn9DKXr4UXxTvLMxTadDNyTUxd89v7UvJoDsxu-NdjqRYjmgbqt_D5E4FhVWXQ6bZsgZuPudiHJxf2L5BDRv6rfC9K9P9apByEGhFOKlce3Zfgw3iQEwUZUYQWXTHIRP9qL0gSCFfxE1XS85vCfOTYFeJKE9ng7WJ6grTWo0KQCqdhT4d25D5X0X9bbOaKkNtE597j51vglooCVTtU6abi4rM6xFFFbLn1DVdGdJ06bo7E3lQfLg-6nBFYOm5fKwlA'}, {'domain': '.batdongsan.com.vn', 'expiry': 1786412042, 'httpOnly': False, 'name': '__eoi', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'ID=a14e9505418fa62a:T=1770860042:RT=1770860042:S=AA-Afjbhb8UklymGsyLRDQGxM3Id'}, {'domain': '.batdongsan.com.vn', 'expiry': 1773452061, 'httpOnly': False, 'name': '__su', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': '0'}, {'domain': '.batdongsan.com.vn', 'expiry': 1804556042, 'httpOnly': False, 'name': '__gpi', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'UID=000011fc297b5600:T=1770860042:RT=1770860042:S=ALNI_MbuyCamK9DnmFux0yF27gdma58e8Q'}, {'domain': '.batdongsan.com.vn', 'expiry': 1805420035, 'httpOnly': False, 'name': '__uidac', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '01698d2e03cd50bbb2efa7089da7190b'}, {'domain': '.batdongsan.com.vn', 'expiry': 1804556042, 'httpOnly': False, 'name': '__gads', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'ID=359f599171b17380:T=1770860042:RT=1770860042:S=ALNI_MbGNPsUl9zQDrWKW_V9DZbdPHfgBQ'}, {'domain': '.batdongsan.com.vn', 'httpOnly': True, 'name': '_cfuvid', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'G5XJAcK6sjT7W7TZjbyS4QnQ1yvsdj2n_tX0lUYGEfc-1770860041737-0.0.1.1-604800000'}, {'domain': '.batdongsan.com.vn', 'expiry': 1773452061, 'httpOnly': False, 'name': '__iid', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': '6461'}, {'domain': 'batdongsan.com.vn', 'expiry': 1771464865, 'httpOnly': False, 'name': 'AWSALBCORS', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'c4ULBky4r3nBzDTRJ246oFj5deCNaObiY9mTKm4bovURN/5mBcKw55hwk0beSVMTgq1wL/DaNyxjRfZhshIBUduLaJDXSl8KLWglibzEx75y6RHd2H/fyrua5jHw'}, {'domain': '.batdongsan.com.vn', 'expiry': 1770861835, 'httpOnly': False, 'name': '_hjSession_1708983', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'eyJpZCI6IjM1ODI1OWViLTUzYTQtNDVhMC1iYTA5LWQ1ZjJkNzVhMjRlMCIsImMiOjE3NzA4NjAwMzU1MjgsInMiOjAsInIiOjAsInNiIjowLCJzciI6MCwic2UiOjAsImZzIjoxLCJzcCI6MH0='}, {'domain': 'batdongsan.com.vn', 'expiry': 1770861865, 'httpOnly': False, 'name': 'con.ses.id', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '8ceb8b10-28df-4124-8f2b-d7e2dda29f82'}, {'domain': '.batdongsan.com.vn', 'expiry': 1805420050, 'httpOnly': False, 'name': 'ab.storage.userId.892f88ed-1831-42b9-becb-90a189ce90ad', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '%7B%22g%22%3A%224546453%22%2C%22c%22%3A1770860050684%2C%22l%22%3A1770860050686%7D'}, {'domain': '.batdongsan.com.vn', 'expiry': 1802396046, 'httpOnly': True, 'name': 'refreshToken', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'jcdaaZvmc_hgt-pn03hdFFG4l_Nhlje5U1qDNcoKjew'}, {'domain': '.batdongsan.com.vn', 'expiry': 1804556061, 'httpOnly': False, 'name': '_tt_enable_cookie', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '1'}, {'domain': '.batdongsan.com.vn', 'expiry': 1778636035, 'httpOnly': False, 'name': '_gcl_au', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '1.1.2017572335.1770860036'}, {'domain': '.batdongsan.com.vn', 'expiry': 1773452035, 'httpOnly': False, 'name': '__admUTMtime', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '1770860035'}, {'domain': '.batdongsan.com.vn', 'expiry': 1804556067, 'httpOnly': False, 'name': 'ttcsid_CHHL1E3C77U1H95PSJM0', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '1770860035986::4n2hCmXG6BdAwwAyF9Ec.1.1770860067153.1'}, {'domain': 'batdongsan.com.vn', 'expiry': 1773452034, 'httpOnly': False, 'name': 'con.unl.sc', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '1'}]

In [15]:
from dotenv import load_dotenv
import json 
import os 

load_dotenv()

users = os.getenv("ACCOUNT_USERNAMES").split(",")
passwords = os.getenv("ACCOUNT_PASSWORDS").split(",")

accounts = list(zip(users, passwords))
print(accounts)

[('0328765904', 'Vyatran123'), ('admin', 'admin456')]

In [16]:
type(accounts)

list

Phone Scraping:
- Tạo một pool bao gồm toàn bộ clone accounts (khoảng 5 accounts) và lưu lại browser cookies của mỗi account. Vì rate limit được áp dụng thông qua Account chứ không phải IP nên cần tạo 2 queues khác nhau: Available Accounts và Cooldown Accounts.
- Tạo thêm một function để spawn worker cho việc trích xuất SĐT.
- Việc trích xuất SĐT sẽ được thực hiện sau khi đã hoàn thành xong việc trích xuất toàn bộ các thông tin cơ bản khác (trước bước cleaning) để tránh việc bị rate limit làm hỏng pipeline. 
- Các bước thực hiện:
1. Query DB để lọc ra những dòng có SĐT = null.
2. Lần lượt log in vào các accounts và save browser cookies.
3. Scrape khoảng tầm 5 SĐT (liên tục check network để detect rate limit) và switch sang account khác.

- Vì việc scrape SĐT bị limit RẤT nặng nên phải cân nhắc việc tạo một table riêng trong database với 2 giá trị: SĐT và account người đăng. Khi scrape SĐT, nếu detect được người đăng này đã có sẵn số trong DB thì không cần phải scrape lại để bị rate limit làm chi.

To-do list:
- Fix lại cleaning theo rules mới. 
- Nếu đúng là Wi-Fi bị ngắt, trước tiên thử tìm dây mạng để cắm vô và chạy test lại. Nếu vẫn không được, thử chia nhỏ job ra để chạy trong khoảng 5:30 - 7:00 của các ngày trong tuần, đồng thời bổ sung thêm việc check internet liên tục trong pipeline.
- Test việc rotate giữa các tài khoản để trích xuất số điện thoại liên hệ trong bài đăng của batdongsan.com
- Chỉnh sửa cách insert trong db (việc của PML).

# Sửa lại cleaning rules

In [5]:
bds_raw.head(1)

,id,url,title,short_address,address_parts,latitude,longitude,main_info,description,other_info,image_urls
0,44957949,https://batdongsan.com.vn/ban-nha-rieng-duong-vinh-loc-xa-vinh-loc-b/-dep-4-12m-2-ngan-2pn-2wc-hem-oto-lh-xem-nha-pr44957949,Nhà Đẹp 4*12m 2/ngắn Đường Vĩnh Lộc 2PN 2WC Hẻm oto Lh 0762 717 *** xem nhà,"Đường Vĩnh Lộc, Xã Vĩnh Lộc B, Bình Chánh, Hồ Chí Minh","[""Bán"", ""Hồ Chí Minh"", ""Bình Chánh"", ""Nhà riêng tại đường Vĩnh Lộc""]",10.798405,106.559937,"[{""title"": ""Khoảng giá"", ""value"": ""1,95 tỷ"", ""ext"": ""~40,62 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""48 m²"", ""ext"": ""1 tầng""}, {""title"": ""Phòng ngủ"", ""value"": ""2 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""05/01/2026"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""20/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""44957949"", ""ext"": null}]","Hạ 200tr Chính chủ gửi Nhà đẹp 2/ ngắn Đường Vĩnh Lộc gần Chợ Vĩnh Lộc và Trung Tâm Ngã 5 Vĩnh Lộc.\r\n- DT: 4*12m\r\n- Thiết kế: 1 trệt 1 lầu 2PN 2WC\r\n- Hẻm 4,5m ô tô\r\n- Khu dân cư hiện hữu\r\n- Nhà có Hồ Sơ Xã Ký\r\n#Giá: 1ty950 TL\r\nLiên hệ\r\n0762 717 ***\r\nxem nhà","{""Khoảng giá"": ""1,95 tỷ"", ""Diện tích"": ""48 m²"", ""Số phòng ngủ"": ""2 phòng"", ""Số phòng tắm, vệ sinh"": ""2 phòng"", ""Số tầng"": ""1 tầng"", ""Đường vào"": ""5 m"", ""Pháp lý"": ""Hợp đồng mua bán"", ""Nội thất"": ""Cơ bản""}","[""https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105124021-3e67_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105124022-a6ff_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105124022-8caa_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105124023-6ac3_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105124024-8104_wm.jpg""]"

In [6]:
bds_raw["description"].str.contains("diện tích xây dựng", case=False).sum()

np.int64(628)

In [7]:
bds_raw["description"].str.contains("dtxd", case=False).sum()

np.int64(306)

In [9]:
bds_raw.shape

(124933, 11)

In [15]:
dtxd = bds_raw[bds_raw["description"].str.contains("dtxd", case=False)]

In [16]:
dtxd.head(5)

,id,url,title,short_address,address_parts,latitude,longitude,main_info,description,other_info,image_urls
368,44741965,https://batdongsan.com.vn/ban-nha-rieng-duong-van-cao-phuong-lieu-giai/sieu-hiem-8-8ty-4-5t-moi-dep-mat-ngo-chinh-cach-mp-15m-ba-gac-vao-dt28-33m-mt-3-5m-pr44741965,"SIÊU HIẾM 8,8TỶ NHÀ 4,5T MỚI ĐẸP MẶT NGÕ CHÍNH CÁCH MP VĂN CAO 15M BA GÁC VÀO, DT28/33M MT 3,5M","Đường Văn Cao, Phường Liễu Giai, Ba Đình, Hà Nội","[""Bán"", ""Hà Nội"", ""Ba Đình"", ""Nhà riêng tại đường Văn Cao""]",21.039847,105.816082,"[{""title"": ""Khoảng giá"", ""value"": ""8,8 tỷ"", ""ext"": ""~314,29 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""28 m²"", ""ext"": ""Mặt tiền 3.5 m""}, {""title"": ""Phòng ngủ"", ""value"": ""3 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""30/12/2025"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""14/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""44741965"", ""ext"": null}]","CHỈ 8,8TỶ SỞ HỮU NHÀ 4 TẦNG MỚI NỘI THẤT ĐẸP, XỊN SÒ DÂN XÂY Ở MẶT NGÕ VĂN CAO CÁCH MẶT PHỐ 15M.\r\n\r\n- Nhà nằm vị trí trung tâm đắc địa gần nút giao Văn Cao - Liễu Giai - Đội Cấn.\r\n\r\n- Khu lõi VÍP của Ba Đình đi bộ 3 phút tới CV Thủ Lệ, Hồ Tây, sắp đón tuyến tầu điện Văn Cao - Hoà Lạc tăng thêm giá trị.\r\n\r\n- Ngõ đẹp thẳng tắp ra phố rộng 3 xe máy tránh nhau thoải mái.\r\n\r\n- Ngõ thông, sáng, thoáng văn minh, nhà nằm trên mặt ngõ chính chỉ cách mặt phố 15m không ngoắt ngéo. 3333Rất phù hợp làm văn phòng, bán hàng Onlie...\r\n\r\n- Dt sổ đỏ 28m dtxd 33m mặt tiền 3,5m khổ đất đẹp vuông vắn.\r\n\r\n+ Nhà dân xây để ở cực chắc chắn kiên cố cẩn thận.\r\n\r\n+ Thiết kế và kiến trúc hiện đại trẻ trung, chủ mới làm lại gói nội thất tiền tỷ.\r\n\r\n+ Tầng 1 bếp và phòng khách.\r\n\r\n+ Tầng 2,3,4 là mỗi tầng 1 pn 1 wc khép kín.\r\n\r\n+ Tum phòng thờ sân phơi.\r\n\r\n+ Nội thất đầy đủ khách mang quần áo đến ở. Căn nhà siêu hiếm trong phân khúc dưới 10tỷ.\r\n\r\nSĐCC pháp lý sạch giao nhà ngay. LH: Mr Hiệp\r\n0903 445 ***","{""Khoảng giá"": ""8,8 tỷ"", ""Diện tích"": ""28 m²"", ""Số phòng ngủ"": ""3 phòng"", ""Số phòng tắm, vệ sinh"": ""4 phòng"", ""Số tầng"": ""5 tầng"", ""Mặt tiền"": ""3,5 m"", ""Đường vào"": ""2,5 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng"", ""Nội thất"": ""Đầy đủ""}","[""https://file4.batdongsan.com.vn/crop/600x315/2025/12/08/20251208104943-9fbd_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/12/08/20251208104944-d231_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/12/08/20251208104946-43e2_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/12/08/20251208104948-dff4_wm.jpg""]"
997,44958471,https://batdongsan.com.vn/ban-nha-rieng-duong-binh-quoi-phuong-28/71tr-m2-ban-gap-53m2-dtxd-gia-chi-3-8-ty-co-pn-tret-pr44958471,71tr/m2: Bán gấp nhà 53m2 DTXD - giá chỉ 3.8 tỷ - có PN trệt,"Đường Bình Quới, Phường 28, Bình Thạnh, Hồ Chí Minh","[""Bán"", ""Hồ Chí Minh"", ""Bình Thạnh"", ""Nhà riêng tại đường Bình Quới""]",10.825236,106.733827,"[{""title"": ""Khoảng giá"", ""value"": ""3,8 tỷ"", ""ext"": ""~71,7 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""53 m²"", ""ext"": ""1 tầng""}, {""title"": ""Phòng ngủ"", ""value"": ""2 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""05/01/2026"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""20/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""44958471"", ""ext"": null}]","71tr/m²: Bán gấp nhà 53m² DTXD - giá chỉ 3.8 tỷ - có PN trệt.\r\n- Giá: 3.8 tỷ thương lượng.\r\n\r\n- Bình Quới, P28, Bình Thạnh.\r\n- DT xây dựng: 53m² công nhận đủ, 5x11m.\r\n- Sổ hồng riêng, hỗ trợ vay bank.\r\n- Nhà 2PN, phòng khách lớn, bếp, sân rộng.\r\n\r\nLiên hệ:\r\n0394 122 ***\r\n- Hoàng Gia.\r\nChuyên nhận ký gửi bán nhà đất Bình Thạnh, Phú Nhuận, Gò Vấp.","{""Khoảng giá"": ""3,8 tỷ"", ""Diện tích"": ""53 m²"", ""Số phòng ngủ"": ""2 phòng"", ""Số phòng tắm, vệ sinh"": ""2 phòng"", ""Số tầng"": ""1 tầng"", ""Hướng nhà"": ""Đông - Nam"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng""}","[""https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105140014-ad81_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105140015-5112_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105140015-d292_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105140015-4f35_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2026/01/05/20260105140014-5bb8_wm.jpg""]"
1113,44515194,https://batdongsan.com.vn/ban-nha-rieng-duong-xuan-thoi-son-31-xa-xuan-thoi-son-prj-khu-do-thi-moi-xuan-thoi-son/-hoc-mon-ngang-5mxdai-20m-tong-96-5m2-1-ngan-31-moi-pr44515194,"Nhà Hóc Môn, ngang 5mxdài 20m tổng 96,5m2 ,1/ ngắn đường Xuân Thới Sơn 31, xã Xuân Thới Sơn (mới).","Xuân Thới Sơn, Đường Xuân Thới Sơn 31, Xã Xuân Thới Sơn, Hóc Môn, Hồ Chí Minh","[""Bán"", ""Hồ Chí Minh"", ""Hóc Môn"", ""Nhà riêng tại Khu đô thị mới Xuân Thới Sơn""]",10.879056,106.551777,"[{""title"": ""Khoảng giá"", ""value"": ""5,3 tỷ"", ""ext"": ""~41,7 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""127,1 m²"", ""ext"": ""Mặt tiền 5 m""}, {""title"": ""Phòng ngủ"", ""value"": ""3 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""28/12/2025"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""12/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""44515194"", ""ext"": null}]","Chủ kẹt tiền cần bán gấp căn nhà 1 trệt 1 lầu , xã Xuân Thới Sơn, huyện Hóc Môn, Hồ Chí Minh (Cũ).\r\n\r\nDiện tích nhà: 5mx20m, công nhận 127,1m², DTXD: 96,5M2\r\nHiện trạng nhà: nhà đẹp như trong tranh, công năng đầy đủ gồm 3 phòng, 2 toilet, sân xe hơi, phòng khách rộng rãi, phòng bếp xịn sò, có giếng trời bào thoáng, chỉ việc dọn vào ở.\r\nVị trí: nằm 1 sẹc đường Xuân Thới Sơn 31, cách tầm 40m. Hẻm ô tô ra vào đc, nhà đậu ô tô thoải mái. Nhà gần trường học cấp 1-2-3, Ủy Ban, gần chợ, thích hợp cho khách mua về ở ngay hoặc mua đầu tư sinh lời.\r\nPháp lý: Sổ hồng riêng.\r\nGiá: 5,3 tỷ đồng, thương lượng khách thiện chí.\r\n\r\n* Bất động sản Huỳnh Gia:\r\n- Nhận ký gửi, mua bán nhà đất huyện Hóc Môn, quận 12, Củ Chi, Hồ Chí Minh.\r\n- Hỗ trợ vay ngân hàng,....\r\n- Nhanh chóng, uy tín, trung thực, tận tâm vì khách hàng\r\n\r\nCám ơn đã đọc tin và mong tiếp khách thiện chí./.","{""Khoảng giá"": ""5,3 tỷ"", ""Diện tích"": ""127,1 m²"", ""Số phòng ngủ"": ""3 phòng"", ""Số phòng tắm, vệ sinh"": ""2 phòng"", ""Số tầng"": ""2 tầng"", ""Hướng nhà"": ""Nam"", ""Hướng ban công"": ""Nam"", ""Mặt tiền"": ""5 m"", ""Đường vào"": ""8 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng"", ""Nội thất"": ""Cơ bản""}","[""https://file4.batdongsan.com.vn/crop/600x315/2025/11/11/20251111102610-221b_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/11/11/20251111102610-483f_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/11/11/20251111102610-1516_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/11/11/20251111102610-d510_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/11/11/20251111102610-7eda_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/11/11/20251111102610-f286_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/11/11/20251111102611-fcfe_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/11/11/20251111102611-2a11_wm.jpg""]"
1291,44906676,https://batdongsan.com.vn/ban-nha-rieng-duong-nguyen-hong-phuong-lang-ha/-4-5t-ngo-47-pho-t-ngo-17-huynh-thuc-khang-oto-tranh-he-3m-canh-vuon-hoa-dt-42m-pr44906676,"NHÀ 4,5T NGÕ 47 PHỐ NGUYÊN HỒNG THÔNG NGÕ 17 HUỲNH THÚC KHÁNG OTO TRÁNH HÈ 3M, CẠNH VƯỜN HOA DT 42M","Đường Nguyên Hồng, Phường Láng Hạ, Đống Đa, Hà Nội","[""Bán"", ""Hà Nội"", ""Đống Đa"", ""Nhà riêng tại đường Nguyên Hồng""]",21.016103,105.809682,"[{""title"": ""Khoảng giá"", ""value"": ""18,8 tỷ"", ""ext"": ""~447,62 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""42 m²"", ""ext"": ""Mặt tiền 4 m""}, {""title"": ""Phòng ngủ"", ""value"": ""6 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""28/12/2025"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""12/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""44906676"", ""ext"": null}]","NHÀ 4,5 TẦNG PHÂN LÔ VIP NGÕ 47 PHỐ NGUYÊN HỒNG THÔNG NGÕ 17 HUỲNH THÚC KHÁNG, CẠNH SÂN CHƠI - VƯỜN HOA SÂN CHƠI.\r\n\r\n- Thuộc khu phân lô vip Nam Thành Công, sở hữu Full các tiện ích như công viên Thành Công, bể bơi, sân chơi, trường cấp 1.2.3 Nam Thành Công.\r\n\r\n- Vị trí trung tâm đắc địa lõi quận Đống Đa mấy bước chân sang Ba Đình, có hạ tầng quần thể đẹp khang trang, văn minh.\r\n\r\n- Ngõ đẹp nhất nhì của phố đường bàn cờ oto tránh nhau dừng đỗ thoải mái có vỉa hè hai bên rộng mỗi bên 3m.\r\n\r\n- Dt sổ đỏ 42m dtxd 46m mặt tiền rộng gần 4m khổ đất đẹp vuông vắn.\r\n\r\n+ Nhà dân xây để ở cực kiên cố chắc chắn cẩn thận.\r\n\r\n+ Thiết kế tầng 1 là gara oto và bếp.\r\n\r\n+ Tầng 2,3,4 là 2pn 1wc. Tầng 5 phòng thờ sân phơi.\r\n\r\nGia chủ rất thiện trí bán giá 18,8tỷ SĐCC thuộc phân khúc siêu hiếm tại khu này.\r\n\r\nLH: Mr Hiệp\r\n0903 445 ***","{""Khoảng giá"": ""18,8 tỷ"", ""Diện tích"": ""42 m²"", ""Số phòng ngủ"": ""6 phòng"", ""Số phòng tắm, vệ sinh"": ""4 phòng"", ""Số tầng"": ""5 tầng"", ""Mặt tiền"": ""4 m"", ""Đường vào"": ""9 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng"", ""Nội thất"": ""Đầy đủ""}","[""https://file4.batdongsan.com.vn/crop/600x315/2025/12/27/20251227144558-add8_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/12/27/20251227144603-b4dc_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/12/27/20251227144605-8183_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/12/27/20251227144558-641d_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/12/27/20251227144559-39f3_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/12/27/20251227144600-e09e_wm.jpg""]"
1321,44913556,https://batdongsan.com.vn/ban-nha-rieng-duong-tran-van-long-phuong-an-khanh-1/b-gap-3pn-3wc-tai-thoi-nhut-2-khh-ninh-kieu-c-tho-8-7-ty-pr44913556,"Bán gấp Nhà riêng 3PN, 3WC tại Trần Văn Long, Thới Nhựt 2, An Khánh, Ninh Kiều, Cần Thơ, 8,7 tỷ","Đường Trần Văn Long, Phường An Khánh, Ninh Kiều, Cần Thơ","[""Bán"", ""Cần Thơ"", ""Ninh Kiều"", ""Nhà riêng tại đường Trần Văn Long""]",10.043071,105.754995,"[{""title"": ""Khoảng giá"", ""value"": ""8,7 tỷ"", ""ext"": ""~56,13 triệu/m²""}, {""title"": ""Diện tích"", ""value"": ""155 m²"", ""ext"": ""Mặt tiền 8 m""}, {""title"": ""Phòng ngủ"", ""value"": ""3 PN"", ""ext"": null}, {""title"": ""Ngày đăng"", ""value"": ""28/12/2025"", ""ext"": null}, {""title"": ""Ngày hết hạn"", ""value"": ""12/01/2026"", ""ext"": null}, {""title"": ""Loại tin"", ""value"": ""Tin thường"", ""ext"": null}, {""title"": ""Mã tin"", ""value"": ""44913556"", ""ext"": null}]","Nhà riêng 155m², 1 tầng tại Trần Văn Long, An Khánh, Ninh Kiều, Cần Thơ.\r\n\r\n- Diện tích: 155m2\r\n- Giá: 8,7 tỷ VND\r\n- 3 phòng ngủ, 3 phòng tắm\r\n- Hướng cửa chính: Tây Nam, hướng ban công: Tây Nam\r\n- Mặt tiền rộng 8m, ngõ trước rộng 19m\r\n- Nội thất đầy đủ: điều hòa, giường, tủ lạnh...\r\n\r\nGiá 8,7 tỷ TL\r\nBán nhà mặt tiền đầu đường Trần Văn Long, KDC Thới Nhựt 2.\r\nDTĐ: 155,3 mét (8x20), DTXD: 95,3 mét, DTSD: 200,37 mét.\r\nNhà trệt, 1 lầu, nhưng xây 2 mâm đúc, tường 20 rất kiên cố. Có 1 nhà xe, 3PN, 1 PK, bếp.\r\n\r\nĐiểm nổi bật:\r\n- Phong thủy tốt, phù hợp với gia chủ\r\n- Đường vào rộng rãi, thuận tiện cho xe ô tô\r\n- Mặt tiền thích hợp cho việc kinh doanh\r\n- Pháp lý đầy đủ\r\n\r\nĐịa điểm xung quanh:\r\n- Gần công viên KDC An Khánh\r\n- Bệnh viện Trường Đại Học Y Dược Cần Thơ, Bệnh viện Đa Khoa Trung Ương Cần Thơ, Bệnh viện Quốc Tế Phương Châu\r\n- Siêu thị Mẹ Bầu & Em Bé Con Cưng, Bách Hóa Xanh\r\n- Các trung tâm dạy học như Mendy Nguyễn Music Class, Vinabacus Cần Thơ\r\n\r\nLiên hệ để biết thêm thông tin: Minh Quân -\r\n0899 445 ***\r\n.","{""Khoảng giá"": ""8,7 tỷ"", ""Diện tích"": ""155 m²"", ""Số phòng ngủ"": ""3 phòng"", ""Số phòng tắm, vệ sinh"": ""3 phòng"", ""Số tầng"": ""1 tầng"", ""Hướng nhà"": ""Tây - Nam"", ""Hướng ban công"": ""Tây - Nam"", ""Mặt tiền"": ""8 m"", ""Đường vào"": ""19 m"", ""Pháp lý"": ""Sổ đỏ/ Sổ hồng"", ""Nội thất"": ""Đầy đủ""}","[""https://file4.batdongsan.com.vn/crop/600x315/2025/12/28/20251228232938-e128_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/12/28/20251228232939-14c4_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/12/28/20251228232940-5855_wm.jpg"", ""https://file4.batdongsan.com.vn/crop/600x315/2025/12/28/20251228232941-187b_wm.jpg""]"

In [17]:
from Batdongsan.cleaning import DataCleaner
import json
import numpy as np 

def extract_total_area(row):
        if pd.notna(row.get("main_info")):
            try:
                for item in json.loads(row["main_info"]):
                    if item.get("title") == "Diện tích":
                        area = DataCleaner._parse_and_clean_number(item.get("value"))
                        if pd.notna(area):
                            return area
            except json.JSONDecodeError:
                pass

        if pd.notna(row.get("other_info")):
            try:
                area_val = json.loads(row["other_info"]).get("Diện tích")
                area = DataCleaner._parse_and_clean_number(area_val)
                if pd.notna(area):
                    return area
            except (json.JSONDecodeError, TypeError):
                pass

        return np.nan

In [ ]:
import re 

def extract_construction_area(row):
    text = str(row.get("description") or "").lower().strip()
    land_area = DataCleaner.extract_total_area(row)

    # Tìm diện tích xây dựng trong bài viết 
    """
    Rules:
    - 
    """
    pattern = r"(?:diện tích xây dựng|dtxd)[\s:.,\-–]"

    # Tìm diện tích thổ cư/đất ở trong bài theo từ khóa              
    # m = r"\b(\d{1,3}(?:[.,]\d{1,2})?)\s?m(?:²|2)(?:\s?\([^)]+\))?\s?(?:full\s)?(?:thổ cư|đất ở)"
    # m2 = r"(?:thổ cư|đất ở|full\s?thổ cư)[\s:.,\-–]{0,3}(\d{1,3}(?:[.,]\d{1,2})?)\s?m(?:²|2)"

    # if m in text:
    #     return round(float(m.group(1).replace(",", ".")), 2)
    # elif m2 in text:
    #     return round(float(m2.group(1).replace(",", ".")), 2)

    # # Trong trường hợp không tìm được diện tích thổ cư/đất ở cụ thể trong bài, mặc định diện tích xây dựng = diện tích đất
    # kws = ["full thổ cư", "thổ cư 100%", "thổ cư hoàn toàn", "toàn bộ thổ cư", "thổ cư toàn bộ"]
    # for kw in kws:
    #     if kw in text:
    #         return land_area

    # matches = re.findall(r"\b\w+\s+thổ cư\s+\w+\b", text, re.IGNORECASE)
    # for match in matches:
    #     for kw in kws:
    #         score = fuzz.ratio(match.lower(), kw.lower())
            # if score > 55:
            #     return land_area       
    
    not_residential_land = ["đất trồng, đất vườn"]
    for keyword in not_residential_land:
        if keyword not in text:
            return land_area
        
        return None