In [48]:
import pandas as pd
from commons.config import *
from main import process_batdongsan_df, process_onehousing_df
from Batdongsan.address_standardizer import AddressStandardizer
import re
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [3]:
# bds = pd.read_csv(DETAILS_CSV_PATH['Batdongsan'])
# oh = pd.read_csv(DETAILS_CSV_PATH['Onehousing'])

standardizer = AddressStandardizer(
            PROVINCES_SQL_FILE, DISTRICTS_SQL_FILE, 
            WARDS_SQL_FILE, STREETS_SQL_FILE
        )

bds_clean = process_batdongsan_df(standardizer=standardizer)
oh_clean = process_onehousing_df()

Ground truth file not found.
Dropped 14 duplicated rows for Batdongsan.
Dropped 882 NaN rows for Batdongsan.
Final number of rows for Batdongsan: 104
[OneHousing] Starting data cleaning...
[OneHousing] Data cleaning completed.
Dropped 1 duplicated rows for Onehousing.
Final number of rows for Onehousing: 999

In [5]:
oh_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, 0 to 999
Data columns (total 33 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Tỉnh/Thành phố                        999 non-null    object
 1   Thành phố/Quận/Huyện/Thị xã           999 non-null    object
 2   Xã/Phường/Thị trấn                    0 non-null      float64
 3   Đường phố                             999 non-null    object
 4   Chi tiết                              999 non-null    object
 5   Nguồn thông tin                       999 non-null    object
 6   Tình trạng giao dịch                  999 non-null    object
 7   Thời điểm giao dịch/rao bán           0 non-null      float64
 8   Thông tin liên hệ                     999 non-null    object
 9   Giá rao bán/giao dịch                 999 non-null    float64
 10  Giá ước tính                          999 non-null    float64
 11  Loại đơn giá (đ/m2 hoặc đ/m ngang)    999 non-null    object
 12  Đơn giá đất                           999 non-null    object
 13  Lợi thế kinh doanh                    999 non-null    object
 14  Số tầng công trình                    984 non-null    float64
 15  Tổng diện tích sàn                    999 non-null    float64
 16  Đơn giá xây dựng                      925 non-null    float64
 17  Năm xây dựng                          0 non-null      float64
 18  Chất lượng còn lại                    999 non-null    object
 19  Diện tích đất (m2)                    999 non-null    float64
 20  Kích thước mặt tiền (m)               994 non-null    float64
 21  Kích thước chiều dài (m)              994 non-null    float64
 22  Số mặt tiền tiếp giáp                 999 non-null    int64
 23  Hình dạng                             999 non-null    object
 24  Độ rộng ngõ/ngách nhỏ nhất (m)        867 non-null    float64
 25  Khoảng cách tới trục đường chính (m)  999 non-null    float64
 26  Mục đích sử dụng đất                  999 non-null    object
 27  Yếu tố khác                           999 non-null    object
 28  Tọa độ (vĩ độ)                        0 non-null      float64
 29  Tọa độ (vĩ độ)                        0 non-null      float64
 30  Tọa độ (kinh độ)                      0 non-null      float64
 31  Tọa độ (kinh độ)                      0 non-null      float64
 32  Hình ảnh của bài đăng                 999 non-null    object
dtypes: float64(17), int64(1), object(15)
memory usage: 265.4+ KB

In [9]:
oh_clean.iloc[0]

Tỉnh/Thành phố                                                           Thành phố Hà Nội
Thành phố/Quận/Huyện/Thị xã                                               Huyện Thanh Trì
Xã/Phường/Thị trấn                                                                    NaN
Đường phố                                                                       Tân Triều
Chi tiết                                                                          Mặt ngõ
Nguồn thông tin                         https://onehousing.vn/bds/Nha-mat-ngo-cach-Tan...
Tình trạng giao dịch                                                       Đang giao dịch
Thời điểm giao dịch/rao bán                                                           NaN
Thông tin liên hệ
Giá rao bán/giao dịch                                                        5850000000.0
Giá ước tính                                                                 5733000000.0
Loại đơn giá (đ/m2 hoặc đ/m ngang)                                                   đ/m2
Đơn giá đất
Lợi thế kinh doanh
Số tầng công trình                                                                    5.0
Tổng diện tích sàn                                                                  115.0
Đơn giá xây dựng                                                                8221171.0
Năm xây dựng                                                                          NaN
Chất lượng còn lại                                                                   0.85
Diện tích đất (m2)                                                                   23.0
Kích thước mặt tiền (m)                                                               3.0
Kích thước chiều dài (m)                                                             7.67
Số mặt tiền tiếp giáp                                                                   1
Hình dạng                                                                        Chữ nhật
Độ rộng ngõ/ngách nhỏ nhất (m)                                                        2.0
Khoảng cách tới trục đường chính (m)                                                 50.0
Mục đích sử dụng đất                                                                Đất ở
Yếu tố khác
Tọa độ (vĩ độ)                                                                        NaN
Tọa độ (vĩ độ)                                                                        NaN
Tọa độ (kinh độ)                                                                      NaN
Tọa độ (kinh độ)                                                                      NaN
Hình ảnh của bài đăng                   https://rs.onehousing.vn/fast/320x0/filters:qu...
Name: 0, dtype: object

# Inspect Onehousing

## Code address standardizer

In [12]:
import argparse
import sqlite3

class AddressStandardizer:
    def __init__(self, provinces_sql_path: str, districts_sql_path: str, wards_sql_path: str, streets_sql_path: str):
        self.reverse_province_map = {}
        self.reverse_district_map = {}
        self.provinces_sql_path = provinces_sql_path
        self.districts_sql_path = districts_sql_path
        self.wards_sql_path = wards_sql_path
        self.streets_sql_path = streets_sql_path
        self._load_data()

    def _load_data(self):
        try:
            conn = sqlite3.connect(":memory:")
            conn.execute("CREATE TABLE provinces (name TEXT, code TEXT, status TEXT);")
            conn.execute("CREATE TABLE districts (name TEXT, code TEXT, province_code TEXT, status TEXT);")
            conn.execute("CREATE TABLE wards (name TEXT, code TEXT, district_code TEXT, status TEXT);")
            conn.execute("CREATE TABLE streets (name TEXT, code TEXT, district_code TEXT, status TEXT);")

            with open(self.provinces_sql_path, "r", encoding="utf-8") as f:
                conn.executescript(f.read())

            with open(self.districts_sql_path, "r", encoding="utf-8") as f:
                dis_cleaned = f.read().replace("\\'", "''")
                conn.executescript(dis_cleaned)

            with open(self.wards_sql_path, "r", encoding="utf-8") as f:
                ward_cleaned = f.read().replace("\\'", "''")
                conn.executescript(ward_cleaned)

            with open(self.streets_sql_path, "r", encoding="utf-8") as f:
                street_cleaned = f.read().replace("'\\'", "''")
                street_cleaned = f.read().replace("'\'", "''")
                conn.executescript(street_cleaned)

            provinces_df = pd.read_sql_query("SELECT * FROM provinces", conn)

            districts_df = pd.read_sql_query("""
                SELECT d.name AS district_name, p.name AS province_name
                FROM districts d
                JOIN provinces p ON d.province_code = p.code
                """, conn)
            
            wards_df = pd.read_sql_query("""
                SELECT w.name AS ward_name,
                    d.name AS district_name,
                    p.name AS province_name
                FROM wards w
                JOIN districts d ON w.district_code = d.code
                JOIN provinces p ON d.province_code = p.code
            """, conn)

        except (FileNotFoundError, sqlite3.Error) as e:
            print(f"Error: Could not load administrative data. Details: {e}")
            raise
        finally:
            if 'conn' in locals():
                conn.close()

        # Build reverse lookup maps
        self.reverse_province_map = {
            prov.replace("Thành phố ", "").replace("Tỉnh ", ""): prov
            for prov in provinces_df['name'].unique()
        }
        self.reverse_province_map['Bà Rịa Vũng Tàu'] = 'Tỉnh Bà Rịa - Vũng Tàu'

        self.reverse_district = {}
        for province in districts_df['province_name'].unique():
            self.reverse_district[province] = {}
            for district_name in districts_df[districts_df['province_name'] == province]['district_name'].unique():
                district_name_strip = district_name.replace('Thành phố ', '').replace('Thành Phố ', '').replace('Quận ', '').replace('Huyện ', '').replace('Thị xã ', '').replace('Thị Xã ', '').strip()
                self.reverse_district[province][district_name_strip] = district_name
        self.reverse_district['Tỉnh Bà Rịa - Vũng Tàu']['Long Đất'] = 'Huyện Long Đất'
        self.reverse_district['Thành phố Hồ Chí Minh']['Quận 2'] = 'Thành phố Thủ Đức'
        self.reverse_district['Thành phố Hồ Chí Minh']['Quận 9'] = 'Thành phố Thủ Đức'

        self.reverse_ward = {}
        for province in self.reverse_district.keys():
            self.reverse_ward[province] = {}
            for district in self.reverse_district[province].values():
                self.reverse_ward[province][district] = {}
                for ward in wards_df[wards_df['district_name'] == district]['ward_name'].unique():
                    ward_name_strip = normalize('NFC', ward.replace('Xã ', '').replace('Phường ', '').replace('Thị trấn ', '').replace('Thị Trấn ', '').strip())
                    self.reverse_ward[province][district][ward_name_strip] = ward
        
        self.districts = districts_df
        self.wards = wards_df

    def standardize_province(self, province_name):
        if not isinstance(province_name, str):
            return province_name
        province_name = province_name.replace('.', '')
        province_name = province_name.replace(',', '')
        province_name = province_name.replace('?', '')
        province_name = province_name.replace('!', '')
        return self.reverse_province_map.get(province_name, province_name)

    def standardize_district(self, row):
            prefix = ['Thành phố', 'Thành Phố', 'Quận', 'Huyện', 'Thị xã', 'Thị Xã', 'Đảo']
            district_value = row['Thành phố/Quận/Huyện/Thị xã']

            if isinstance(district_value, str):
                if district_value == 'Quận 2' or district_value == 'Quận 9':
                    return 'Thành phố Thủ Đức'
                for pre in prefix:
                    if district_value.startswith(pre):
                        return district_value
                province = row['Tỉnh/Thành phố']
                if district_value in self.reverse_district[province].keys():
                    return self.reverse_district[province][district_value]
                for dis in self.reverse_district[province].keys():
                    similarity = fuzz.ratio(district_value, dis)
                    if similarity >= 66:
                        return self.reverse_district[province][dis]
                return None
            return None

    def standardize_ward(self, row):
        ward_value = row['Xã/Phường/Thị trấn']

        def matching(ward_value, district_value, province_value):
            # Function to match values with its corresponding prefixes
            if ward_value in self.reverse_ward[province_value][district_value].keys():
                return self.reverse_ward[province_value][district_value][ward_value]
            for ward in self.reverse_ward[province_value][district_value].keys():
                similarity = fuzz.ratio(ward_value, ward)
                if similarity >= 66:
                    return self.reverse_ward[province_value][district_value][ward]
            return None
                
        if ward_value:
            prefix = ['Xã', 'Phường', 'Thị trấn', 'Thị Trấn']
            for pre in prefix:
                if ward_value.startswith(pre):
                    return ward_value
            ward_value = normalize('NFC', ward_value)
            district_value = row['Thành phố/Quận/Huyện/Thị xã']
            province_value = row['Tỉnh/Thành phố']
            return matching(ward_value, district_value, province_value)
        else:
            short_add = row['short_address']
            if isinstance(short_add, str) and short_add != '':
                if 'xã' in short_add.lower():
                    match_result = re.search(pattern='(xã [\w\s]+)', string=short_add.lower())
                    if match_result:
                        match_result = match_result[0]
                        result_split = match_result.split()
                        result = ' '.join(i.capitalize() for i in result_split)
                        return result
                elif 'phường' in short_add.lower():
                    match_result = re.search(pattern='(phường [\w\s]+)', string=short_add.lower())
                    if match_result:
                        match_result = match_result[0]
                        result_split = match_result.split()
                        result = ' '.join(i.capitalize() for i in result_split)
                        return result
                elif 'thị trấn' in short_add.lower():
                    match_result = re.search(pattern='(thị trấn [\w\s]+)', string=short_add.lower())
                    if match_result:
                        match_result = match_result[0]
                        result_split = match_result.split()
                        result = ' '.join(i.capitalize() for i in result_split)
                        return result
                else:
                    short_add_list = row['short_address'].split(',')
                    if len(short_add_list) >= 3:
                        new_province_val = row['Tỉnh/Thành phố']
                        new_ward_val = normalize('NFC',short_add_list[-3].strip())
                        new_district_val = row['Thành phố/Quận/Huyện/Thị xã']
                        return matching(new_ward_val, new_district_val, new_province_val)

            else:
                return None
            
        return None

## Code Onehousing cleaner

In [ ]:
from Onehousing.orchestrator import (
    scrape_onehousing_urls as oh_scrape_urls, 
    scrape_onehousing_details as oh_scrape_details
)

standardizer = AddressStandardizer(
            PROVINCES_SQL_FILE, DISTRICTS_SQL_FILE, 
            WARDS_SQL_FILE, STREETS_SQL_FILE
        )

class OneHousingDataCleaner:
    """
    Cleans and transforms raw OneHousing scraped data into standardized format.
    """

    @staticmethod
    def _extract_city(row):
        """Extract and standardize city name."""
        city = row.get('city')
        if pd.notna(city):
           return str(row["city"]).replace("TP.", "Thành phố").replace('T.', 'Tỉnh').strip()
        else:
            city = row.get('listing_title', '')
            try:
                return city.split(',')[-1].replace('TP.', 'Thành phố').replace('T.', 'Tỉnh').strip()
            except:
                return np.nan
        # return np.nan
        # if pd.notna(row.get("city")):
            

        # title = str(row.get("listing_title", ""))
        # match = re.search(r"(TP\.|Thành phố)\s*([^.,\n]+)", title, re.IGNORECASE)

        # return f"Thành phố {match.group(2).strip()}" if match else np.nan

    @staticmethod
    def _extract_district(row):
        """Extract and standardize district name."""
        district = row.get("district")

        if pd.notna(district):
            return str(district).replace("Q.", "Quận").replace("H.", "Huyện").replace("TX.", "Thị xã").strip()

        title = row.get('listing_title', '')
        if pd.notna(title):
            return title.split(",")[-2].replace('TP.').replace('Q.', "Quận").replace('H.', "Huyện").replace('TX.', 'Thị xã').strip()
        return np.nan
        # title = str(row.get("listing_title", ""))
        # match = re.search(r"\b(Q\.|H\.|TX\.)\s*([^.,\n]+)", title, re.IGNORECASE)

        # if match:
        #     prefix, name = match.group(1).upper(), match.group(2).strip()
        #     if prefix == "Q.":
        #         return f"Quận {name}"
        #     if prefix == "H.":
        #         return f"Huyện {name}"
        #     if prefix == "TX.":
        #         return f"Thị xã {name}"

        # return np.nan

    @staticmethod
    def _extract_ward(df):
        """Extract ward/commune information."""
        def extract_row(row):
            full_address = row.get('listing_title', '')
            district = row.get('district', '')

            if pd.isna(full_address) or not isinstance(full_address, str) or \
                    pd.isna(district) or not isinstance(district, str):
                return np.nan

            address_list = full_address.split(",")
            try:
                ward = address_list[-3].replace("X.", "Xã").replace("P.", "Phường").replace("TT.", "Thị trấn").strip()
                return ward
            except:
                return np.nan

        return df.apply(extract_row, axis=1)

    @staticmethod
    def _extract_street_name(series: pd.Series) -> pd.Series:
        """Extract street name from listing title."""
        def extract(text: str):
            if pd.isna(text):
                return np.nan

            patterns = [
                r"(?:Nhà mặt ngõ|Đất nền|Nhà trong ngõ).*?cách\s+(.*?)\s*\d+(?:\.\d+)?m",
                r"(?:Nhà mặt phố|Mặt đường)\s+([^,]+?)\s*,",
                r"Đất nền\s+((?!.*cách)[^,]+?)\s*,"
            ]

            for p in patterns:
                if match := re.search(p, str(text), re.IGNORECASE):
                    return re.sub(r'\s*\(.*\)\s*$', '', match.group(1).strip()).strip()
            return np.nan

        return series.apply(extract)

    @staticmethod
    def _classify_property_type(title: str) -> str:
        """Classify property as street-front or alley."""
        if pd.isna(title):
            return ""

        if "cách" in str(title).lower():
            return "Mặt ngõ"

        return "Mặt phố"

    @staticmethod
    def _convert_price_to_numeric(price_str: str) -> float:
        """Convert price string to numeric value."""
        if pd.isna(price_str):
            return np.nan

        price = str(price_str).lower()

        try:
            val_str = price.replace(',', '.').strip()
            if 'tỷ' in val_str:
                return float(val_str.replace('tỷ', '').strip()) * 1e9
            if 'triệu' in val_str:
                return float(val_str.replace('triệu', '').strip()) * 1e6
            return float(val_str)
        except (ValueError, AttributeError):
            return np.nan

    @staticmethod
    def _estimate_price(price: float) -> float:
        """Estimate actual price (98% of listed price)."""
        return round(price * 0.98, 2) if pd.notna(price) else np.nan

    @staticmethod
    def _extract_alley_width(row):
        """Extract minimum alley width."""
        for text in [row.get("alley_width"), row.get("property_description")]:
            if pd.notna(text):
                if nums := re.findall(r"(\d+(?:\.\d+)?)", str(text)):
                    try:
                        return min(float(n) for n in nums)
                    except ValueError:
                        continue
        return np.nan

    @staticmethod
    def _extract_front_width(row):
        """Extract front width from features or description."""
        sources = [row.get('features'), row.get('property_description')]
        patterns = [
            r"Hướng mặt tiền\s*:[^;-]+?-\s*(\d+(?:\.\d+)?)\s*m",
            r"Nhà mặt tiền\s+(\d+(?:\.\d+)?)\s*m"
        ]
        for text in sources:
            if pd.notna(text):
                for p in patterns:
                    if match := re.search(p, str(text), re.IGNORECASE):
                        try:
                            return float(match.group(1))
                        except ValueError:
                            pass
        return np.nan

    @staticmethod
    def _extract_number_of_floors(row):
        """Extract total number of floors."""
        title = str(row.get("listing_title", "")).lower()
        if "đất nền" in title:
            return 0.0

        text = str(row.get("features", "")) + " " + str(row.get("property_description", ""))
        floor = re.search(r"Số tầng:\s*(\d+(?:\.\d+)?)", text, re.IGNORECASE)
        basement = re.search(r"Số tầng hầm:\s*(\d+(?:\.\d+)?)", text, re.IGNORECASE)
        total_floors = 0.0
        found = False

        if floor:
            total_floors += float(floor.group(1))
            found = True
        if basement:
            total_floors += float(basement.group(1))
            found = True

        return total_floors if found else np.nan

    @staticmethod
    def _extract_land_area(row):
        """Extract land area."""
        text = str(row.get("features", "")) + " " + str(row.get("property_description", ""))
        patterns = [r"Diện tích:\s*(\d+(?:\.\d+)?)", r"diện tích đất thực tế là\s*([\d.]+)m²"]

        for p in patterns:
            if match := re.search(p, text, re.IGNORECASE):
                try:
                    return float(match.group(1))
                except (ValueError, IndexError):
                    pass

        return np.nan

    @staticmethod
    def _extract_distance_to_main_road(row):
        """Extract distance to main road."""
        desc = str(row.get('property_description', ''))
        title = str(row.get('listing_title', ''))

        if 'mặt phố' in title.lower():
            return 0

        patterns = [
            r"khoảng cách ra trục đường chính\s*(\d+(?:\.\d+)?)\s*m",
            r"cách\s+.*?\s+(\d+(?:\.\d+)?)\s*m"
        ]
        text_sources = [desc, title]

        for text, p in zip(text_sources, patterns):
            if match := re.search(p, text, re.IGNORECASE):
                return float(match.group(1))

        return 0

    @staticmethod
    def _extract_number_of_frontages(row):
        """Extract number of frontages."""
        text = row.get("property_description")
        if pd.isna(text):
            return 1

        match = re.search(r"(\d+)\s*mặt tiền", str(text), re.IGNORECASE)
        if match:
            try:
                return int(match.group(1))
            except (ValueError, IndexError):
                pass

        return 1

    @staticmethod
    def _estimate_remaining_quality(row):
        """Estimate remaining quality of construction."""
        title = str(row.get("listing_title", "")).lower()

        if "đất nền" in title:
            return ""
        return 0.85

    @staticmethod
    def _estimate_construction_price(row):
        """Estimate construction price per sqm."""
        text = str(row.get("features", "")) + " " + str(row.get("property_description", ""))
        floor = re.search(r"Số tầng:\s*(\d+(?:\.\d+)?)", text, re.IGNORECASE)
        basement = re.search(r"Số tầng hầm:\s*(\d+(?:\.\d+)?)", text, re.IGNORECASE)
        total_floors = 0.0

        if "đất nền" in text:
            return ""

        total_floors += float(floor.group(1)) if floor else 0.0
        total_floors += float(basement.group(1)) if basement else 0.0

        if total_floors == 1:
            return 6275876

        if basement and float(basement.group(1)) > 0:
            return 9504604

        if total_floors > 1:
            return 8221171
        
        return np.nan

    @staticmethod
    def clean_onehousing_data(df: pd.DataFrame) -> pd.DataFrame:
        """
        Apply all cleaning transformations to OneHousing raw data.
        
        Args:
            df: DataFrame with raw OneHousing data
            
        Returns:
            Cleaned DataFrame in standardized format
        """
        print("[OneHousing] Starting data cleaning...")
        
        # Rename property_id to ID for consistency
        if 'property_id' in df.columns:
            df = df.copy()
            df.rename(columns={'property_id': 'ID'}, inplace=True)
        
        # Extract and transform all fields
        city = df.apply(OneHousingDataCleaner._extract_city, axis=1)
        district = df.apply(OneHousingDataCleaner._extract_district, axis=1)
        
        # Temporarily add district column for location extraction
        df_temp = df.copy()
        df_temp['district'] = district
        location = OneHousingDataCleaner._extract_ward(df_temp)
        
        street = OneHousingDataCleaner._extract_street_name(df["listing_title"])
        prop_type = df["listing_title"].apply(OneHousingDataCleaner._classify_property_type)
        price = df["total_price"].apply(OneHousingDataCleaner._convert_price_to_numeric)
        est_price = price.apply(OneHousingDataCleaner._estimate_price)
        floors = df.apply(OneHousingDataCleaner._extract_number_of_floors, axis=1)
        num_frontages = df.apply(OneHousingDataCleaner._extract_number_of_frontages, axis=1)
        area = df.apply(OneHousingDataCleaner._extract_land_area, axis=1)
        front_width = df.apply(OneHousingDataCleaner._extract_front_width, axis=1)
        remaining_quality = df.apply(OneHousingDataCleaner._estimate_remaining_quality, axis=1)
        construction_price = df.apply(OneHousingDataCleaner._estimate_construction_price, axis=1)

        with np.errstate(divide='ignore', invalid='ignore'):
            floors_for_calc = floors.fillna(1.0)
            total_area = round((floors_for_calc * area).replace([np.inf, -np.inf], np.nan), 2)
            length = round((area / front_width).replace([np.inf, -np.inf], np.nan), 2)

        cleaned_df = pd.DataFrame({
            "Tỉnh/Thành phố": city,
            "Thành phố/Quận/Huyện/Thị xã": district,
            "Xã/Phường/Thị trấn": location,
            "Đường phố": street,
            "Chi tiết": prop_type,
            "Nguồn thông tin": df["property_url"],
            "Tình trạng giao dịch": "Đang rao bán",
            "Thời điểm giao dịch/rao bán": np.nan,
            "Thông tin liên hệ": np.nan,
            "Giá rao bán/giao dịch": price,
            "Giá ước tính": est_price,
            "Loại đơn giá (đ/m2 hoặc đ/m ngang)": "đ/m2",
            "Đơn giá đất": np.nan,
            "Lợi thế kinh doanh": np.nan,
            "Số tầng công trình": floors,
            "Tổng diện tích sàn": total_area,
            "Đơn giá xây dựng": construction_price,
            "Năm xây dựng": np.nan,
            "Chất lượng còn lại": remaining_quality,
            "Diện tích đất (m2)": area,
            "Kích thước mặt tiền (m)": front_width,
            "Kích thước chiều dài (m)": length,
            "Số mặt tiền tiếp giáp": num_frontages,
            "Hình dạng": "Chữ nhật",
            "Độ rộng ngõ/ngách nhỏ nhất (m)": df.apply(OneHousingDataCleaner._extract_alley_width, axis=1),
            "Khoảng cách tới trục đường chính (m)": df.apply(OneHousingDataCleaner._extract_distance_to_main_road, axis=1),
            "Mục đích sử dụng đất": "Đất ở",
            "Yếu tố khác": df['property_description'],
            "Tọa độ (vĩ độ)": np.nan,
            "Tọa độ (kinh độ)": np.nan,
            "Hình ảnh của bài đăng": df["image_url"]
        })
        
        print("[OneHousing] Data cleaning completed.")
        test_df = cleaned_df[['Tỉnh/Thành phố', 
        'Thành phố/Quận/Huyện/Thị xã', 
        'Xã/Phường/Thị trấn', 
        'Đường phố', 
        'Chi tiết', 
        'Nguồn thông tin', 
        'Tình trạng giao dịch',
        'Thời điểm giao dịch/rao bán',
        'Thông tin liên hệ',
        'Giá rao bán/giao dịch',
        'Giá ước tính',
        'Loại đơn giá (đ/m2 hoặc đ/m ngang)',
        'Đơn giá đất',
        'Lợi thế kinh doanh',
        'Số tầng công trình',
        'Tổng diện tích sàn',
        'Đơn giá xây dựng',
        'Năm xây dựng',
        "Chất lượng còn lại",
        "Diện tích đất (m2)",
        "Kích thước mặt tiền (m)",
        "Kích thước chiều dài (m)",
        "Số mặt tiền tiếp giáp",
        "Hình dạng",
        "Độ rộng ngõ/ngách nhỏ nhất (m)",
        "Khoảng cách tới trục đường chính (m)",
        "Mục đích sử dụng đất",
        "Yếu tố khác",
        "Tọa độ (vĩ độ)",
        "Tọa độ (kinh độ)",
        "Hình ảnh của bài đăng"]]
        test_df['listing_title'] = df['listing_title']
        test_df['property_description'] = df['property_description']

        return cleaned_df, test_df


# def process_onehousing_df():
#     """Cleaning logic for OneHousing CSV data."""
#     raw_path = DETAILS_CSV_PATH['Onehousing']
#     if not raw_path.exists():
#         return pd.DataFrame()

#     df_raw = pd.read_csv(raw_path)
#     df = OhCleaner.clean_onehousing_data(df_raw)
    
#     # # Apply standardizer to address columns
#     # df['Tỉnh/Thành phố'] = df['Tỉnh/Thành phố'].apply(standardizer.standardize_province)
#     # df['Thành phố/Quận/Huyện/Thị xã'] = df.apply(standardizer.standardize_district, axis=1)
#     # df['Xã/Phường/Thị trấn'] = df.apply(standardizer.standardize_ward, axis=1)
    
#     # Missing coordinates in OH
#     if 'latitude' not in df.columns: df['latitude'] = np.nan
#     if 'longitude' not in df.columns: df['longitude'] = np.nan

#     # Rename to standardized schema
#     oh_final = df.rename(columns={v: k for k, v in FINAL_SCHEMA.items() if v in df.columns})
#     oh_final = oh_final[list(FINAL_SCHEMA.keys())]

#     # Drop NaN and duplicated values
#     na = [
#         'Tỉnh/Thành phố',
#         'Thành phố/Quận/Huyện/Thị xã',
#         'Xã/Phường/Thị trấn',
#         'Đường phố',
#         'Chi tiết',
#         'Nguồn thông tin', 
#         'Thời điểm giao dịch/rao bán',
#         'Giá rao bán/giao dịch',
#         'Giá ước tính',
#         'Số tầng công trình', 
#         'Tổng diện tích sàn', 
#         'Đơn giá xây dựng',
#         'Chất lượng còn lại',
#         'Diện tích đất (m2)',
#         'Kích thước mặt tiền (m)',
#         'Kích thước chiều dài (m)',
#         'Số mặt tiền tiếp giáp',
#         'Hình dạng',
#         'Độ rộng ngõ/ngách nhỏ nhất (m)',
#         'Khoảng cách tới trục đường chính (m)',
#         'Mục đích sử dụng đất',
#         'Tọa độ (vĩ độ)',
#         'Tọa độ (kinh độ)'
#     ]
#     dup = [
#         'Tỉnh/Thành phố', 
#         'Thành phố/Quận/Huyện/Thị xã', 
#         'Xã/Phường/Thị trấn', 
#         'Đường phố', 
#         'Giá rao bán/giao dịch', 
#         'Giá ước tính', 
#         'Số tầng công trình', 
#         'Tổng diện tích sàn', 
#         'Đơn giá xây dựng', 
#         'Chất lượng còn lại', 
#         'Diện tích đất (m2)', 
#         'Kích thước mặt tiền (m)', 
#         'Kích thước chiều dài (m)', 
#         'Số mặt tiền tiếp giáp', 
#         'Hình dạng', 
#         'Độ rộng ngõ/ngách nhỏ nhất (m)', 
#         'Khoảng cách tới trục đường chính (m)', 
#         'Mục đích sử dụng đất'
#     ]

#     old_size = oh_final.shape[0]
#     oh_final.drop_duplicates(subset=dup, inplace=True)
#     oh_final.reset_index(drop=True)
#     print(f'Dropped {old_size - oh_final.shape[0]} duplicated rows for Onehousing.')

#     # old_size = oh_final.shape[0]  
#     # oh_final.dropna(subset=na, inplace=True)
#     # print(f'Dropped {old_size - oh_final.shape[0]} NaN rows for Onehousing.')

#     print(f'Final number of rows for Onehousing: {oh_final.shape[0]}')

    # return oh_final

In [37]:
oh = pd.read_csv('output/onehousing_listings_details.csv', header=None)
oh.columns = ['property_url','listing_title','property_id','total_price','unit_price','alley_width','image_url','city','district','features', 'latitude', 'longitude', 'property_description','scraping_time']
oh.to_csv('output/onehousing_listings_details.csv', index=False)

In [6]:
import pandas as pd
from commons.config import *

oh_raw = pd.read_csv(DETAILS_CSV_PATH['Batdongsan'])
oh_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   url            1000 non-null   object
 1   title          1000 non-null   object
 2   id             1000 non-null   int64
 3   latitude       1000 non-null   float64
 4   longitude      1000 non-null   float64
 5   short_address  1000 non-null   object
 6   address_parts  1000 non-null   object
 7   main_info      1000 non-null   object
 8   description    1000 non-null   object
 9   other_info     1000 non-null   object
 10  image_urls     1000 non-null   object
 11  scraping_time  1000 non-null   int64
dtypes: float64(2), int64(2), object(8)
memory usage: 93.9+ KB

In [4]:
from Onehousing.cleaning import OneHousingDataCleaner

oh_cleaned = OneHousingDataCleaner.clean_onehousing_data(oh_raw)
oh_cleaned.info()

[OneHousing] Starting data cleaning...
[OneHousing] Data cleaning completed.
<class 'pandas.core.frame.DataFrame'>
Index: 808 entries, 0 to 998
Data columns (total 31 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Tỉnh/Thành phố                        808 non-null    object
 1   Thành phố/Quận/Huyện/Thị xã           808 non-null    object
 2   Xã/Phường/Thị trấn                    808 non-null    object
 3   Đường phố                             808 non-null    object
 4   Chi tiết                              808 non-null    object
 5   Nguồn thông tin                       808 non-null    object
 6   Tình trạng giao dịch                  808 non-null    object
 7   Thời điểm giao dịch/rao bán           0 non-null      float64
 8   Thông tin liên hệ                     808 non-null    object
 9   Giá rao bán/giao dịch                 808 non-null    float64
 10  Giá ước tính                          808 non-null    float64
 11  Loại đơn giá (đ/m2 hoặc đ/m ngang)    808 non-null    object
 12  Đơn giá đất                           808 non-null    object
 13  Lợi thế kinh doanh                    808 non-null    object
 14  Số tầng công trình                    808 non-null    float64
 15  Tổng diện tích sàn                    808 non-null    float64
 16  Đơn giá xây dựng                      808 non-null    float64
 17  Năm xây dựng                          0 non-null      float64
 18  Chất lượng còn lại                    808 non-null    object
 19  Diện tích đất (m2)                    808 non-null    float64
 20  Kích thước mặt tiền (m)               808 non-null    float64
 21  Kích thước chiều dài (m)              808 non-null    float64
 22  Số mặt tiền tiếp giáp                 808 non-null    int64
 23  Hình dạng                             808 non-null    object
 24  Độ rộng ngõ/ngách nhỏ nhất (m)        808 non-null    float64
 25  Khoảng cách tới trục đường chính (m)  808 non-null    float64
 26  Mục đích sử dụng đất                  808 non-null    object
 27  Yếu tố khác                           808 non-null    object
 28  Tọa độ (vĩ độ)                        0 non-null      float64
 29  Tọa độ (kinh độ)                      0 non-null      float64
 30  Hình ảnh của bài đăng                 808 non-null    object
dtypes: float64(14), int64(1), object(16)
memory usage: 202.0+ KB

Onehousing NaN ở Xã/Phường/Thị trấn, Thời điểm giao dịch/rao bán, Thông tin liên hệ, Đơn giá đất, Lợi thế kinh doanh, Số tầng công trình, Năm xây dựng, Kích thước mặt tiền (m), Kích thước chiều dài (m), Độ rộng ngõ/ngách nhỏ nhất (m), Yếu tố khác, Tọa độ (kinh độ), Tọa độ (vĩ độ)

# Ghép file Batdongsan

In [16]:
import pandas as pd

old_bds = pd.read_excel('output/old_bds.xlsx')
old_bds_not_drop_na = pd.read_excel('output/old_bds_raw.xlsx')
old_bds_raw = pd.read_csv('output/listing_urls.csv')

new_bds = pd.read_csv('output/batdongsan_listing_urls.csv')

In [17]:
df = pd.concat([old_bds_raw, new_bds], axis=0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60068 entries, 0 to 1519
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   url     60068 non-null  object
dtypes: object(1)
memory usage: 938.6+ KB

In [26]:
yo = pd.read_csv('output/onehousing_listing_urls.csv', header=None)
yo[0].tolist()

['https://onehousing.vn/bds/Nha-mat-ngo-cach-Hoang-Nhu-Tiep-40m--P--Bo-De--Q--Long-Bien--TP--Ha-Noi.UQPHMR',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Doi-Can-50m--P--Doi-Can--Q--Ba-Dinh--TP--Ha-Noi.TPGLJ0',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngo-Thi-Nham-50m--P--Ha-Cau--Q--Ha-Dong--TP--Ha-Noi.BUZJOR',
 'https://onehousing.vn/bds/Nha-mat-pho-Khuong-Trung--P--Khuong-Trung--Q--Thanh-Xuan--TP--Ha-Noi.YBOFZL',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Vinh-Tuy-30m--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.GBNVWC',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Dai-Tu-80m--P--Dai-Kim--Q--Hoang-Mai--TP--Ha-Noi.U0NJMC',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Tan-Mai-50m--P--Thinh-Liet--Q--Hoang-Mai--TP--Ha-Noi.C5PRYW',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Le-Van-Luong-50m--P--Trung-Hoa--Q--Cau-Giay--TP--Ha-Noi.BATVNQ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Duong-Dang-Cong-Chat-100m--TT--Yen-Vien--H--Gia-Lam--TP--Ha-Noi.RT8VQ1',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Duong-Dang-Cong-Chat-50m--TT--Yen-Vien--H--Gia-Lam--TP--Ha-Noi.YIEQAQ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Dai-Tu-50m--X--Kim-Chung--H--Hoai-Duc--TP--Ha-Noi.XOE6DL',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Dai-Tu-200m--X--Kim-Chung--H--Hoai-Duc--TP--Ha-Noi.6XYXQH',
 'https://onehousing.vn/bds/Nha-mat-pho-Bach-Dang--P--Thanh-Luong--Q--Hai-Ba-Trung--TP--Ha-Noi.3XYMRI',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Co-Linh-209-82m--P--Thach-Ban--Q--Long-Bien--TP--Ha-Noi.0SYWHQ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Vu-Dinh-Tung-189m--P--Thach-Ban--Q--Long-Bien--TP--Ha-Noi.PXXKNK',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Tan-Ap-50m--P--Phuc-Xa--Q--Ba-Dinh--TP--Ha-Noi.RAD1KB',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Duong-Van-Be-60m--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.CLKKWK',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Lam-30m--P--Ngoc-Lam--Q--Long-Bien--TP--Ha-Noi.LU3FNC',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Cau-Dien-50m--P--Tay-Tuu--Q--Bac-Tu-Liem--TP--Ha-Noi.BCOCNB',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Thuy-10m--P--Ngoc-Thuy--Q--Long-Bien--TP--Ha-Noi.L7R7UX',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Dinh-50m--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.SKUOOI',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Thai-Thinh-30m--P--Thinh-Quang--Q--Dong-Da--TP--Ha-Noi.NKHHRZ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Dong-Ngac-130m--P--Dong-Ngac--Q--Bac-Tu-Liem--TP--Ha-Noi.AJTSI9',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Ha-50m--P--Ngoc-Ha--Q--Ba-Dinh--TP--Ha-Noi.UMXDQL',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Bo-De-100m--P--Bo-De--Q--Long-Bien--TP--Ha-Noi.ENIVCB',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Ha-30m--P--Ngoc-Ha--Q--Ba-Dinh--TP--Ha-Noi.L4UKJP',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Dinh-40m--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.X4KURM',
 'https://onehousing.vn/bds/Dat-nen-cach-Ton-Duc-Thang-200m--P--Van-Chuong--Q--Dong-Da--TP--Ha-Noi.JMOPT3',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Thuy-20m--P--Ngoc-Thuy--Q--Long-Bien--TP--Ha-Noi.LDGVZH',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ai-Mo-15m--P--Bo-De--Q--Long-Bien--TP--Ha-Noi.VJUZBJ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Bat-Khoi--Mat-de-song-Hong--30m--P--Thach-Ban--Q--Long-Bien--TP--Ha-Noi.NB9BRX',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Van-Linh-20m--P--Long-Bien--Q--Long-Bien--TP--Ha-Noi.S7IPGM',
 'https://onehousing.vn/bds/Dat-nen-cach-Tan-Phong-50m--P--Thuy-Phuong--Q--Bac-Tu-Liem--TP--Ha-Noi.PIOIYW',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Dinh-120m--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.2VUH6W',
 'https://onehousing.vn/bds/Dat-nen-cach-Nguyen-Truc-300m--P--Phu-Luong--Q--Ha-Dong--TP--Ha-Noi.TMJUY6',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Khuong-Trung-20m--P--Khuong-Trung--Q--Thanh-Xuan--TP--Ha-Noi.MDTGAN',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Dinh-Thon-20m--P--My-Dinh-1--Q--Nam-Tu-Liem--TP--Ha-Noi.CANWRH',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-To-Huu-10m--P--Trung-Van--Q--Nam-Tu-Liem--TP--Ha-Noi.ZH3C2W',
 'https://onehousing.vn/bds/Dat-nen-cach-Nguyen-Truc-300m--P--Phu-Luong--Q--Ha-Dong--TP--Ha-Noi.OIRAJL',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Hoang-Cong-50m--P--Kien-Hung--Q--Ha-Dong--TP--Ha-Noi.QLZF7X',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Vuong-Thua-Vu-50m--P--Khuong-Trung--Q--Thanh-Xuan--TP--Ha-Noi.QUEODH',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Pham-Van-Nghi-20m--P--Co-Nhue-2--Q--Bac-Tu-Liem--TP--Ha-Noi.DKI3CA',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Phuc-Loi-150m--P--Phuc-Loi--Q--Long-Bien--TP--Ha-Noi.5JJKJX',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Thanh-Am-20m--P--Thuong-Thanh--Q--Long-Bien--TP--Ha-Noi.93ER7V',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-My-Dinh-120m--P--My-Dinh-1--Q--Nam-Tu-Liem--TP--Ha-Noi.QGVUT5',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Dinh-Thon-50m--P--My-Dinh-1--Q--Nam-Tu-Liem--TP--Ha-Noi.3GLXNM',
 'https://onehousing.vn/bds/Dat-nen-Duong-Van-Be--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.N09SKG',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Hoang-Van-Thai-50m--P--Khuong-Trung--Q--Thanh-Xuan--TP--Ha-Noi.O3MMCM',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Kham-Thien-30m--P--Trung-Phung--Q--Dong-Da--TP--Ha-Noi.L7XEMC',
 'https://onehousing.vn/bds/Dat-nen-cach-Hoang-Nhu-Tiep-90m--P--Bo-De--Q--Long-Bien--TP--Ha-Noi.1CJ7BU',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Bo-De-40-14m--P--Bo-De--Q--Long-Bien--TP--Ha-Noi.HQRTHT',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Linh-Dam-100m--P--Hoang-Liet--Q--Hoang-Mai--TP--Ha-Noi.IC06WJ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Duong-Phan-Trong-Tue-100m--X--Ta-Thanh-Oai--H--Thanh-Tri--TP--Ha-Noi.TWMHD6',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Yen-Hoa-80m--P--Yen-Hoa--Q--Cau-Giay--TP--Ha-Noi.WVKM5I',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Tan-Mai-20m--P--Tan-Mai--Q--Hoang-Mai--TP--Ha-Noi.XWIXQT',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Trinh-Dinh-Cuu-15m--P--Dinh-Cong--Q--Hoang-Mai--TP--Ha-Noi.RZCWLS',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Trung-Van-20m--P--Dai-Mo--Q--Nam-Tu-Liem--TP--Ha-Noi.T8GYAV',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Pho-Nguyen-Lan-20m--P--Phuong-Liet--Q--Thanh-Xuan--TP--Ha-Noi.UUWNOB',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-My-Dinh-100m--P--My-Dinh-1--Q--Nam-Tu-Liem--TP--Ha-Noi.2BN3R9',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Hong-Tien-10-9m--P--Bo-De--Q--Long-Bien--TP--Ha-Noi.MDPM1Y',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Trai-50m--P--Trung-Van--Q--Nam-Tu-Liem--TP--Ha-Noi.MJ0SIK',
 'https://onehousing.vn/bds/Dat-nen-cach-Tay-Mo-80m--P--Tay-Mo--Q--Nam-Tu-Liem--TP--Ha-Noi.F2JSXC',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Chinh-80m--P--Thinh-Liet--Q--Hoang-Mai--TP--Ha-Noi.XFDONM',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Tan-Mai-50m--P--Tan-Mai--Q--Hoang-Mai--TP--Ha-Noi.KXCKCX',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Truong-Chinh-15m--P--Khuong-Thuong--Q--Dong-Da--TP--Ha-Noi.PG7ECP',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Dinh-100m--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.8EK2GR',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ton-Duc-Thang-50m--P--Hang-Bot--Q--Dong-Da--TP--Ha-Noi.ZC0DUN',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngo-Gia-Tu-50m--P--Viet-Hung--Q--Long-Bien--TP--Ha-Noi.XDL0V8',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Van-Vien-100m--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.GYEAAH',
 'https://onehousing.vn/bds/Nha-mat-pho-Nguyen-Khoai--P--Bach-Dang--Q--Hai-Ba-Trung--TP--Ha-Noi.SYK4I7',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Xien-20m--P--Ha-Dinh--Q--Thanh-Xuan--TP--Ha-Noi.GTWNVK',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Phu-My-20m--P--My-Dinh-2--Q--Nam-Tu-Liem--TP--Ha-Noi.T4QECD',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Me-Tri-Thuong-60m--P--Me-Tri--Q--Nam-Tu-Liem--TP--Ha-Noi.C1NDNW',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Duong-Xuan-Phuong-100m--P--Phuong-Canh--Q--Nam-Tu-Liem--TP--Ha-Noi.BCHARV',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Trinh-Luong-300m--P--Phu-Luong--Q--Ha-Dong--TP--Ha-Noi.8RKHJK',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Duong-19-5-100m--P--Van-Quan--Q--Ha-Dong--TP--Ha-Noi.ITRIMH',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Dai-Tu-100m--X--Kim-Chung--H--Hoai-Duc--TP--Ha-Noi.W8FXMQ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Bach-Mai-100m--P--Bach-Mai--Q--Hai-Ba-Trung--TP--Ha-Noi.LMZUGE',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Bach-Mai-10m--P--Bach-Mai--Q--Hai-Ba-Trung--TP--Ha-Noi.SKTLGB',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Minh-Khai-100m--P--Minh-Khai--Q--Hai-Ba-Trung--TP--Ha-Noi.USFNRE',
 'https://onehousing.vn/bds/Nha-mat-pho-Gia-Quat--P--Thuong-Thanh--Q--Long-Bien--TP--Ha-Noi.1GEL9R',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Doi-Can-150m--P--Ngoc-Ha--Q--Ba-Dinh--TP--Ha-Noi.29MAWJ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Bat-Khoi--Mat-de-song-Hong--289-2m--P--Long-Bien--Q--Long-Bien--TP--Ha-Noi.RXCTDU',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ho-Linh-Quang-100m--P--Van-Mieu--Q--Dong-Da--TP--Ha-Noi.LI3HWT',
 'https://onehousing.vn/bds/Nha-mat-pho-Kim-Hoa--P--Kim-Lien--Q--Dong-Da--TP--Ha-Noi.0Y3CSN',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ho-Tung-Mau-80m--P--Phu-Dien--Q--Bac-Tu-Liem--TP--Ha-Noi.OIBQZL',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Do-Nha-100m--P--Tay-Mo--Q--Nam-Tu-Liem--TP--Ha-Noi.FOCVXH',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Quan-Nhan-100m--P--Nhan-Chinh--Q--Thanh-Xuan--TP--Ha-Noi.GUZKIL',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Quang-Tien-100m--P--Tay-Mo--Q--Nam-Tu-Liem--TP--Ha-Noi.5Q3VCU',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Thanh-Nhan-15m--P--Bach-Mai--Q--Hai-Ba-Trung--TP--Ha-Noi.CPYBGE',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Tan-Trieu-100m--X--Tan-Trieu--H--Thanh-Tri--TP--Ha-Noi.BE4WD9',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Le-Thanh-Nghi-16m--P--Dong-Tam--Q--Hai-Ba-Trung--TP--Ha-Noi.BKT9XJ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Lac-Long-Quan-50m--P--Nghia-Do--Q--Cau-Giay--TP--Ha-Noi.KGEYAE',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Bat-Khoi--Mat-de-song-Hong--100m--P--Long-Bien--Q--Long-Bien--TP--Ha-Noi.FPEGSW',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Trieu-Khuc-100m--X--Tan-Trieu--H--Thanh-Tri--TP--Ha-Noi.LYDQQZ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Van-Cu-20m--P--Ngoc-Lam--Q--Long-Bien--TP--Ha-Noi.YRKABL',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Chi-Thanh-100m--P--Lang-Thuong--Q--Dong-Da--TP--Ha-Noi.B2A85K',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Lac-Long-Quan-30m--P--Nghia-Do--Q--Cau-Giay--TP--Ha-Noi.N5VWTP',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Duong-Xuan-La---Xuan-Dinh-100m--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.94HMZA',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Tay-Son-25m--P--Quang-Trung--Q--Dong-Da--TP--Ha-Noi.PCT2MW',
 'https://onehousing.vn/bds/Nha-mat-pho-Van-Tan--P--Hoang-Liet--Q--Hoang-Mai--TP--Ha-Noi.XF2IZU',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Trai-200m--P--Thuong-Dinh--Q--Thanh-Xuan--TP--Ha-Noi.81ILAJ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Tan-Mai-20m--P--Tan-Mai--Q--Hoang-Mai--TP--Ha-Noi.JIMJFG',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Kim-Dong-80m--P--Giap-Bat--Q--Hoang-Mai--TP--Ha-Noi.O4RTCJ',
 'https://onehousing.vn/bds/Nha-mat-pho-Bach-Dang--P--Chuong-Duong--Q--Hoan-Kiem--TP--Ha-Noi.BNCH0W',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Thuy--mat-de-va-duong-gom-chan-de--50m--P--Ngoc-Thuy--Q--Long-Bien--TP--Ha-Noi.61FCRZ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ton-Duc-Thang-30m--P--Van-Chuong--Q--Dong-Da--TP--Ha-Noi.R8MJB7',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Thuy--mat-de-va-duong-gom-chan-de--100m--P--Ngoc-Thuy--Q--Long-Bien--TP--Ha-Noi.A5GLHP',
 'https://onehousing.vn/bds/Dat-nen-cach-Xuan-Khoi-50m--P--Cu-Khoi--Q--Long-Bien--TP--Ha-Noi.ETDITA',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Kim-Ma-50m--P--Kim-Ma--Q--Ba-Dinh--TP--Ha-Noi.JFQYWL',
 'https://onehousing.vn/bds/Dat-nen-cach-Xuan-Khoi-50m--P--Cu-Khoi--Q--Long-Bien--TP--Ha-Noi.COQMW5',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Chanh-5m--P--Trung-Hoa--Q--Cau-Giay--TP--Ha-Noi.EYKN1Z',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-To-Hien-Thanh-15m--P--Pho-Hue--Q--Hai-Ba-Trung--TP--Ha-Noi.QQD9M2',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Dam-Quang-Trung-100m--P--Long-Bien--Q--Long-Bien--TP--Ha-Noi.ELVLPW',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Khoi-100m--P--Cu-Khoi--Q--Long-Bien--TP--Ha-Noi.ZOKKZI',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Duong-Linh-Nam-100m--P--Linh-Nam--Q--Hoang-Mai--TP--Ha-Noi.AJ83C1',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Pho-Tram-100m--P--Long-Bien--Q--Long-Bien--TP--Ha-Noi.GNMETY',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Khoi-80m--P--Thach-Ban--Q--Long-Bien--TP--Ha-Noi.DATHIH',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Lam-30m--P--Ngoc-Lam--Q--Long-Bien--TP--Ha-Noi.JNDM5V',
 'https://onehousing.vn/bds/Nha-mat-pho-Xa-Dan--P--Nam-Dong--Q--Dong-Da--TP--Ha-Noi.TTV3IH',
 'https://onehousing.vn/bds/Nha-mat-pho-Truong-Dinh--P--Tan-Mai--Q--Hoang-Mai--TP--Ha-Noi.JCJILP',
 'https://onehousing.vn/bds/Nha-mat-pho-Tran-Vy--P--Mai-Dich--Q--Cau-Giay--TP--Ha-Noi.ZMBHNE',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Duong-Van-Be-20m--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.2663ZY',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Bo-De-100m--P--Bo-De--Q--Long-Bien--TP--Ha-Noi.4NHRDX',
 'https://onehousing.vn/bds/Dat-nen-Duong-Van-Xuan--X--Duc-Giang--H--Hoai-Duc--TP--Ha-Noi.2TPTCU',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Hoa-Lam-50m--P--Viet-Hung--Q--Long-Bien--TP--Ha-Noi.OAK8XZ',
 'https://onehousing.vn/bds/Nha-mat-pho-Nguyen-Canh-Di--P--Dinh-Cong--Q--Hoang-Mai--TP--Ha-Noi.TFKYWT',
 'https://onehousing.vn/bds/Dat-nen-cach-Ha-Trai-20m--P--Cu-Khoi--Q--Long-Bien--TP--Ha-Noi.YITFNR',
 'https://onehousing.vn/bds/Nha-mat-pho-Huynh-Thuc-Khang--P--Lang-Thuong--Q--Dong-Da--TP--Ha-Noi.SHFWRW',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Lam-30m--P--Ngoc-Lam--Q--Long-Bien--TP--Ha-Noi.TF7CJS',
 'https://onehousing.vn/bds/Dat-nen-cach-Ha-Trai-20m--P--Cu-Khoi--Q--Long-Bien--TP--Ha-Noi.T3EG1K',
 'https://onehousing.vn/bds/Dat-nen-Hoa-Dong--P--Cu-Khoi--Q--Long-Bien--TP--Ha-Noi.AT99MU',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Do-10m--P--Cu-Khoi--Q--Long-Bien--TP--Ha-Noi.Z0S4SX',
 'https://onehousing.vn/bds/Nha-mat-pho-Ho-Tung-Mau--P--Phu-Dien--Q--Bac-Tu-Liem--TP--Ha-Noi.VR5EUP',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Viet-Hung-50m--P--Viet-Hung--Q--Long-Bien--TP--Ha-Noi.AQ0RJ6',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Bach-Mai-200m--P--Bach-Mai--Q--Hai-Ba-Trung--TP--Ha-Noi.6JEZ9M',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Lam-8m--P--Bo-De--Q--Long-Bien--TP--Ha-Noi.P3PLXK',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Minh-Khai-50m--P--Minh-Khai--Q--Hai-Ba-Trung--TP--Ha-Noi.YR6Y7W',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Khu-do-thi-moi-An-Hung-10m--P--Duong-Noi--Q--Ha-Dong--TP--Ha-Noi.UWLXYH',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Phuc-Lai-50m--P--O-Cho-Dua--Q--Dong-Da--TP--Ha-Noi.GKYQOC',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Thuy-Khue-50m--P--Buoi--Q--Tay-Ho--TP--Ha-Noi.MQ4JZZ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Kim-Dong-80m--P--Giap-Bat--Q--Hoang-Mai--TP--Ha-Noi.0HOTVU',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Khang-50m--P--Yen-Hoa--Q--Cau-Giay--TP--Ha-Noi.XEVMGR',
 'https://onehousing.vn/bds/Nha-mat-pho-Ngoc-Thuy--mat-de-va-duong-gom-chan-de---P--Ngoc-Thuy--Q--Long-Bien--TP--Ha-Noi.YYX33V',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Khu-do-thi-thanh-pho-giao-luu-20m--P--Co-Nhue-1--Q--Bac-Tu-Liem--TP--Ha-Noi.GTM3BD',
 'https://onehousing.vn/bds/Nha-mat-pho-Ton-Duc-Thang--P--Van-Chuong--Q--Dong-Da--TP--Ha-Noi.W61L8Z',
 'https://onehousing.vn/bds/Nha-mat-pho-Nguyen-Khuyen--P--Van-Mieu--Q--Dong-Da--TP--Ha-Noi.JZ610Z',
 'https://onehousing.vn/bds/Nha-mat-pho-Bui-Xuong-Trach--P--Khuong-Dinh--Q--Thanh-Xuan--TP--Ha-Noi.T5QKUN',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Kham-Thien-30m--P--Van-Chuong--Q--Dong-Da--TP--Ha-Noi.QGPPBA',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Truong-Chinh-100m--P--Khuong-Thuong--Q--Dong-Da--TP--Ha-Noi.VEVE6E',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-To-Vinh-Dien-20m--P--Khuong-Trung--Q--Thanh-Xuan--TP--Ha-Noi.BZ1KQF',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-To-Vinh-Dien-20m--P--Khuong-Trung--Q--Thanh-Xuan--TP--Ha-Noi.K8NIGX',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-De-To-Hoang-60m--P--Bach-Mai--Q--Hai-Ba-Trung--TP--Ha-Noi.OL2C0P',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Thuy-Khue-50m--P--Buoi--Q--Tay-Ho--TP--Ha-Noi.CQWDAS',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Thanh-Xuan-Bac-50m--P--Thanh-Xuan-Bac--Q--Thanh-Xuan--TP--Ha-Noi.HNH3CD',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Tri-50m--P--Long-Bien--Q--Long-Bien--TP--Ha-Noi.0KYSDL',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Ngoc-Vu-50m--P--Trung-Hoa--Q--Cau-Giay--TP--Ha-Noi.ZS0WXN',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Dinh-70m--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.U0QEWC',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Bat-Khoi-50m--P--Cu-Khoi--Q--Long-Bien--TP--Ha-Noi.FQMJVR',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Cau-Giay-30m--P--Quan-Hoa--Q--Cau-Giay--TP--Ha-Noi.RSMJIO',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Huynh-Thuc-Khang-50m--P--Lang-Thuong--Q--Dong-Da--TP--Ha-Noi.QOIRVE',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Phao-Dai-Lang-50m--P--Lang-Thuong--Q--Dong-Da--TP--Ha-Noi.JURUW3',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Thuy--mat-de-va-duong-gom-chan-de--50m--P--Ngoc-Thuy--Q--Long-Bien--TP--Ha-Noi.HB1JPY',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngoc-Thuy--mat-de-va-duong-gom-chan-de--50m--P--Ngoc-Thuy--Q--Long-Bien--TP--Ha-Noi.SJFCLS',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Luong-The-Vinh-60m--P--Trung-Van--Q--Nam-Tu-Liem--TP--Ha-Noi.PEJX6M',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Le-Thanh-Nghi-20m--P--Bach-Mai--Q--Hai-Ba-Trung--TP--Ha-Noi.DHMUBZ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Phuc-Loi-30m--P--Phuc-Loi--Q--Long-Bien--TP--Ha-Noi.I0RQV4',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Tan-Ap-50m--P--Phuc-Xa--Q--Ba-Dinh--TP--Ha-Noi.VGU8VS',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Phuc-Loi-179-8m--P--Phuc-Loi--Q--Long-Bien--TP--Ha-Noi.4KMZXI',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Hong-Ha-130m--P--Chuong-Duong--Q--Hoan-Kiem--TP--Ha-Noi.CHAODC',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Bach-Dang-80m--P--Bach-Dang--Q--Hai-Ba-Trung--TP--Ha-Noi.V7HN4T',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Luong-Bang-50m--P--Nam-Dong--Q--Dong-Da--TP--Ha-Noi.5ZWB1A',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Hong-Ha-30m--P--Phuc-Xa--Q--Ba-Dinh--TP--Ha-Noi.OT2UAV',
 'https://onehousing.vn/bds/Nha-mat-pho-Hang-Bo--P--Hang-Bo--Q--Hoan-Kiem--TP--Ha-Noi.Y3HQLU',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Phung-Khoang-10m--P--Trung-Van--Q--Nam-Tu-Liem--TP--Ha-Noi.WZBSOJ',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Minh-Khai-200m--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.MAHMES',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Minh-Khai-20m--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.FKM0WR',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Van-Cu-100m--P--Gia-Thuy--Q--Long-Bien--TP--Ha-Noi.KMP1Z8',
 'https://onehousing.vn/bds/Nha-mat-pho-Xuan-Tao--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.IRBBKB',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Nguyen-Khanh-Toan-50m--P--Quan-Hoa--Q--Cau-Giay--TP--Ha-Noi.Y16RXY',
 'https://onehousing.vn/bds/Dat-nen-cach-Nguyen-Khac-Vien-50m--P--Viet-Hung--Q--Long-Bien--TP--Ha-Noi.DGL44S',
 'https://onehousing.vn/bds/Nha-mat-pho-Phu-Vien--P--Bo-De--Q--Long-Bien--TP--Ha-Noi.2PBE6Z',
 'https://onehousing.vn/bds/Nha-mat-ngo-cach-Au-Co-5m--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.TPJLMH',

# Inspect Database

In [1]:
import pandas as pd
import sqlite3

with sqlite3.connect('output/real_estate.db') as conn:
    df = pd.read_sql("SELECT * FROM cleaned", con=conn)

df

,Tỉnh/Thành phố,Thành phố/Quận/Huyện/Thị xã,Xã/Phường/Thị trấn,Đường phố,Chi tiết,Nguồn thông tin,Tình trạng giao dịch,Thời điểm giao dịch/rao bán,Thông tin liên hệ,Giá rao bán/giao dịch,...,Số mặt tiền tiếp giáp,Hình dạng,Độ rộng ngõ/ngách nhỏ nhất (m),Khoảng cách tới trục đường chính (m),Mục đích sử dụng đất,Yếu tố khác,Tọa độ (vĩ độ),Tọa độ (kinh độ),Hình ảnh của bài đăng,Web
0,Thành phố Hồ Chí Minh,Quận 8,Phường 1,Đường Dương Bá Trạc,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,23/12/2025,None,7.500000e+09,...,1,Chữ nhật,3.5,10.0,Đất ở,"Diện tích 58,9m² công nhận đủ,\nNgang 3,9m dài...",10.745337,106.690188,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
1,Thành phố Hồ Chí Minh,Quận Gò Vấp,Phường 9,Đường Lê Văn Thọ,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,25/12/2025,None,6.550000e+09,...,1,Chữ nhật,5.0,10.0,Đất ở,Khu cao tầng hẻm xe hơi ngang hơn 5m hiếm.\nTặ...,10.846724,106.656586,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
2,Thành phố Hà Nội,Quận Tây Hồ,Phường Xuân La,Đường Xuân La,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,23/12/2025,None,2.800000e+10,...,1,Chữ nhật,5.0,10.0,Đất ở,GIÁ 28TỶ - NGOẠI GIAO ĐOÀN - XUÂN LA - TÂY HỒ ...,21.064891,105.806182,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
3,Thành phố Hà Nội,Quận Long Biên,Phường Phúc Lợi,Đường Phúc Lợi,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,28/12/2025,None,6.700000e+09,...,2,Chữ nhật,2.5,15.0,Đất ở,"Nhà lô góc 2 mặt thoáng, sáng mát tự nhiên. Di...",21.038674,105.934373,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
4,Thành phố Hà Nội,Quận Tây Hồ,Phường Phú Thượng,Đường Phú Thượng,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,30/12/2025,None,1.180000e+10,...,1,Chữ nhật,4.5,100.0,Đất ở,RẺ NHẤT KHU VỰC. CẦN BÁN NHÀ DÂN XÂY 3T 60M2. ...,21.083858,105.808483,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6892,Thành phố Hà Nội,Quận Nam Từ Liêm,Phường Cầu Diễn,Hồ Tùng Mậu,Mặt ngõ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ho-...,Đang giao dịch,16/01/2026,None,8.100000e+09,...,1,Chữ nhật,2.0,200.0,Đất ở,None,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
6893,Thành phố Hà Nội,Quận Long Biên,Phường Bồ Đề,Bồ Đề,Mặt ngõ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Bo-...,Đang giao dịch,16/01/2026,None,1.750000e+10,...,1,Chữ nhật,4.0,20.0,Đất ở,None,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
6894,Thành phố Hà Nội,Huyện Gia Lâm,Thị trấn Yên Viên,Đường Hà Huy Tập,Mặt ngõ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Duo...,Đang giao dịch,16/01/2026,None,3.650000e+09,...,1,Chữ nhật,2.0,300.0,Đất ở,None,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
6895,Thành phố Hà Nội,Quận Long Biên,Phường Ngọc Thụy,Ngọc Thụy,Mặt ngõ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngo...,Đang giao dịch,16/01/2026,None,8.600000e+09,...,1,Chữ nhật,2.0,200.0,Đất ở,None,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
6896,Thành phố Hà Nội,Quận Long Biên,Phường Long Biên,Đàm Quang Trung,Mặt phố,https://onehousing.vn/bds/Nha-mat-pho-Dam-Quan...,Đang giao dịch,16/01/2026,None,1.290000e+10,...,1,Chữ nhật,10.0,0.0,Đất ở,None,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6897 entries, 0 to 6896
Data columns (total 32 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Tỉnh/Thành phố                        6897 non-null   object
 1   Thành phố/Quận/Huyện/Thị xã           6897 non-null   object
 2   Xã/Phường/Thị trấn                    6897 non-null   object
 3   Đường phố                             6897 non-null   object
 4   Chi tiết                              6897 non-null   object
 5   Nguồn thông tin                       6897 non-null   object
 6   Tình trạng giao dịch                  6897 non-null   object
 7   Thời điểm giao dịch/rao bán           6897 non-null   object
 8   Thông tin liên hệ                     0 non-null      object
 9   Giá rao bán/giao dịch                 6897 non-null   float64
 10  Giá ước tính                          6897 non-null   int64
 11  Loại đơn giá (đ/m2 hoặc đ/m ngang)    6897 non-null   object
 12  Đơn giá đất                           6088 non-null   float64
 13  Lợi thế kinh doanh                    6088 non-null   object
 14  Số tầng công trình                    6897 non-null   float64
 15  Tổng diện tích sàn                    6897 non-null   float64
 16  Đơn giá xây dựng                      6897 non-null   float64
 17  Năm xây dựng                          0 non-null      object
 18  Chất lượng còn lại                    6897 non-null   float64
 19  Diện tích đất (m2)                    6897 non-null   float64
 20  Kích thước mặt tiền (m)               6897 non-null   float64
 21  Kích thước chiều dài (m)              6897 non-null   float64
 22  Số mặt tiền tiếp giáp                 6897 non-null   int64
 23  Hình dạng                             6897 non-null   object
 24  Độ rộng ngõ/ngách nhỏ nhất (m)        6897 non-null   float64
 25  Khoảng cách tới trục đường chính (m)  6897 non-null   float64
 26  Mục đích sử dụng đất                  6897 non-null   object
 27  Yếu tố khác                           6086 non-null   object
 28  Tọa độ (vĩ độ)                        6897 non-null   float64
 29  Tọa độ (kinh độ)                      6897 non-null   float64
 30  Hình ảnh của bài đăng                 6897 non-null   object
 31  Web                                   6897 non-null   object
dtypes: float64(13), int64(2), object(17)
memory usage: 1.7+ MB

In [4]:
df[df['Web'] == 'Onehousing']['Thời điểm giao dịch/rao bán'].value_counts()

Thời điểm giao dịch/rao bán
16/01/2026    809
Name: count, dtype: int64

In [2]:
import pandas as pd
df_csv = pd.read_csv('output/real_estate_cleaned.csv')
df_csv

,Tỉnh/Thành phố,Thành phố/Quận/Huyện/Thị xã,Xã/Phường/Thị trấn,Đường phố,Chi tiết,Nguồn thông tin,Tình trạng giao dịch,Thời điểm giao dịch/rao bán,Thông tin liên hệ,Giá rao bán/giao dịch,...,Số mặt tiền tiếp giáp,Hình dạng,Độ rộng ngõ/ngách nhỏ nhất (m),Khoảng cách tới trục đường chính (m),Mục đích sử dụng đất,Yếu tố khác,Tọa độ (vĩ độ),Tọa độ (kinh độ),Hình ảnh của bài đăng,Web
0,Thành phố Hồ Chí Minh,Quận 8,Phường 1,Đường Dương Bá Trạc,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,23/12/2025,NaN,7.500000e+09,...,1,Chữ nhật,3.5,10.0,Đất ở,"Diện tích 58,9m² công nhận đủ,\nNgang 3,9m dài...",10.745337,106.690188,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
1,Thành phố Hồ Chí Minh,Quận Gò Vấp,Phường 9,Đường Lê Văn Thọ,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,25/12/2025,NaN,6.550000e+09,...,1,Chữ nhật,5.0,10.0,Đất ở,Khu cao tầng hẻm xe hơi ngang hơn 5m hiếm.\nTặ...,10.846724,106.656586,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
2,Thành phố Hà Nội,Quận Tây Hồ,Phường Xuân La,Đường Xuân La,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,23/12/2025,NaN,2.800000e+10,...,1,Chữ nhật,5.0,10.0,Đất ở,GIÁ 28TỶ - NGOẠI GIAO ĐOÀN - XUÂN LA - TÂY HỒ ...,21.064891,105.806182,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
3,Thành phố Hà Nội,Quận Long Biên,Phường Phúc Lợi,Đường Phúc Lợi,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,28/12/2025,NaN,6.700000e+09,...,2,Chữ nhật,2.5,15.0,Đất ở,"Nhà lô góc 2 mặt thoáng, sáng mát tự nhiên. Di...",21.038674,105.934373,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
4,Thành phố Hà Nội,Quận Tây Hồ,Phường Phú Thượng,Đường Phú Thượng,Mặt ngõ,https://batdongsan.com.vn/ban-nha-rieng-duong-...,Đang rao bán,30/12/2025,NaN,1.180000e+10,...,1,Chữ nhật,4.5,100.0,Đất ở,RẺ NHẤT KHU VỰC. CẦN BÁN NHÀ DÂN XÂY 3T 60M2. ...,21.083858,105.808483,"[""https://file4.batdongsan.com.vn/crop/600x315...",Batdongsan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6892,Thành phố Hà Nội,Quận Nam Từ Liêm,Phường Cầu Diễn,Hồ Tùng Mậu,Mặt ngõ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ho-...,Đang giao dịch,NaN,NaN,8.100000e+09,...,1,Chữ nhật,2.0,200.0,Đất ở,NaN,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
6893,Thành phố Hà Nội,Quận Long Biên,Phường Bồ Đề,Bồ Đề,Mặt ngõ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Bo-...,Đang giao dịch,NaN,NaN,1.750000e+10,...,1,Chữ nhật,4.0,20.0,Đất ở,NaN,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
6894,Thành phố Hà Nội,Huyện Gia Lâm,Thị trấn Yên Viên,Đường Hà Huy Tập,Mặt ngõ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Duo...,Đang giao dịch,NaN,NaN,3.650000e+09,...,1,Chữ nhật,2.0,300.0,Đất ở,NaN,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
6895,Thành phố Hà Nội,Quận Long Biên,Phường Ngọc Thụy,Ngọc Thụy,Mặt ngõ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ngo...,Đang giao dịch,NaN,NaN,8.600000e+09,...,1,Chữ nhật,2.0,200.0,Đất ở,NaN,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing
6896,Thành phố Hà Nội,Quận Long Biên,Phường Long Biên,Đàm Quang Trung,Mặt phố,https://onehousing.vn/bds/Nha-mat-pho-Dam-Quan...,Đang giao dịch,NaN,NaN,1.290000e+10,...,1,Chữ nhật,10.0,0.0,Đất ở,NaN,21.001010,105.866667,https://rs.onehousing.vn/fast/320x0/filters:qu...,Onehousing

In [8]:
for i in range(df_csv.shape[0]):
    if df.iloc[i]['Nguồn thông tin'] != df_csv.iloc[i]['Nguồn thông tin']:
        print('Different')
    else:
        print('Same')

Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same
Same

In [4]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6897 entries, 0 to 6896
Data columns (total 32 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Tỉnh/Thành phố                        6897 non-null   object
 1   Thành phố/Quận/Huyện/Thị xã           6897 non-null   object
 2   Xã/Phường/Thị trấn                    6897 non-null   object
 3   Đường phố                             6897 non-null   object
 4   Chi tiết                              6897 non-null   object
 5   Nguồn thông tin                       6897 non-null   object
 6   Tình trạng giao dịch                  6897 non-null   object
 7   Thời điểm giao dịch/rao bán           6088 non-null   object
 8   Thông tin liên hệ                     0 non-null      float64
 9   Giá rao bán/giao dịch                 6897 non-null   float64
 10  Giá ước tính                          6897 non-null   float64
 11  Loại đơn giá (đ/m2 hoặc đ/m ngang)    6897 non-null   object
 12  Đơn giá đất                           6088 non-null   float64
 13  Lợi thế kinh doanh                    6088 non-null   object
 14  Số tầng công trình                    6897 non-null   float64
 15  Tổng diện tích sàn                    6897 non-null   float64
 16  Đơn giá xây dựng                      6897 non-null   float64
 17  Năm xây dựng                          0 non-null      float64
 18  Chất lượng còn lại                    6897 non-null   float64
 19  Diện tích đất (m2)                    6897 non-null   float64
 20  Kích thước mặt tiền (m)               6897 non-null   float64
 21  Kích thước chiều dài (m)              6897 non-null   float64
 22  Số mặt tiền tiếp giáp                 6897 non-null   int64
 23  Hình dạng                             6897 non-null   object
 24  Độ rộng ngõ/ngách nhỏ nhất (m)        6897 non-null   float64
 25  Khoảng cách tới trục đường chính (m)  6897 non-null   float64
 26  Mục đích sử dụng đất                  6897 non-null   object
 27  Yếu tố khác                           6086 non-null   object
 28  Tọa độ (vĩ độ)                        6897 non-null   float64
 29  Tọa độ (kinh độ)                      6897 non-null   float64
 30  Hình ảnh của bài đăng                 6897 non-null   object
 31  Web                                   6897 non-null   object
dtypes: float64(16), int64(1), object(15)
memory usage: 1.7+ MB

In [7]:
df_csv[df_csv['Yếu tố khác'].isna()]['Web'].value_counts()

Web
Onehousing    809
Batdongsan      2
Name: count, dtype: int64

In [ ]:
from datetime import datetime

print(datetime.now().strftime("%d/%m/%Y"))

16/01/2026

# Test add database

In [1]:
import sqlite3
import pandas as pd
import numpy as np

with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw_old = pd.read_sql("SELECT * FROM bds_raw", con=conn)
    oh_raw_old = pd.read_sql("SELECT * FROM onehousing_raw", con = conn)
    df_old = pd.read_sql("SELECT * FROM cleaned", con=conn)

print(f'BDS RAW: {bds_raw_old.shape}')
print(f'OH RAW: {oh_raw_old.shape}')
print(f'CLEANED RAW: {df_old.shape}')

BDS RAW: (58152, 12)
OH RAW: (869, 13)
CLEANED RAW: (6911, 32)

In [4]:
df['Chi tiết'].unique()

array(['Mặt ngõ', 'Mặt phố', '447', '96', 'Phú Hồng Thịnh 8',
       '925/15 Đường Âu Cơ', 'Ngõ 19', '30/5', 'Số 4 ngõ 5', 'Mỹ Đình 1',
       'Hẻm 413', '214', '3/2', 'Ngõ 17x', 'Ngõ 205', '1/', 'Ngõ 187',
       '7/3', '577 Đường Phạm Văn Bạch', 'Khu đô thị Vĩnh Điềm Trung',
       'Thôn 4', 'Hẻm 38', 'Ngõ 213', 'Ngõ 266', '207 Đường Ngọc Hồi',
       '94/6', 'Ngõ 126', '685', '1/46/ Đặng Thùy Trâm', 'Ngõ 180',
       'Hẻm 1/', '55 Phố Chính Kinh', 'Dự án Green Riverside', 'Hẻm 430',
       'Số 8/233', '45 Đường Liên Khu 1-6', '778', 'Số 50', 'Hẻm 14',
       '11/5', 'Ngõ 20', 'Ngõ 31', 'Hẻm 637', 'Dự án Sài Gòn Mới',
       '86/26', 'KDC Phú Hồng Thịnh 10', 'Hẻm 1056', 'Hẻm 222', '47',
       'Dự án KDC Apec City Center', '56', 'Ngõ 135', 'Hẻm 1x5', 'Ngõ 25',
       'Hẻm 353', 'Ngõ 521', '681/ Đường Âu Cơ', '1K', '111 Đường 9',
       '93 Lò Đúc - Kinh Đô Tower', 'Khu A42',
       'Lô 26BC Đường Lê Hồng Phong', 'Ngõ 147', '1632', '276/3/59',
       'Ngõ 131', '69/40 Đường Nguyễn Công Hoan', 'Ngõ 145', 'Ngõ 305',
       'Ngõ chợ Khâm Thiên', '83', 'Dự án KDC An Bình',
       '671 Hoàng Hoa Thám', 'Ngõ 106', 'KĐT Xa La', '28', '80/',
       'Ngõ 192', 'Hẻm 1333', '778/1F', 'HXH 549', 'Ngõ 110', 'Ngõ 112',
       'Ngõ 95', 'Ngõ Linh Quang', 'Hẻm 243A', 'Ngõ 221', 'HXH 496',
       'Ngõ 101', '15A Đường 10', '280m', '69/', '1879', 'Hẻm 2637',
       'Ngõ 82', 'Hẻm 670', '95 Đường Giang Văn Minh',
       'Dự án Cát Tường Phú Sinh Eco City', '197', '428/53',
       'Dự án Long Kim II', '146//', 'Ngõ 12A', 'Ngõ 59', '5A',
       '93/8 Đường Đô Đốc Long', 'Hẻm 29', 'Ngõ 34',
       'Dự án Xuân Phương Residence', 'Hẻm 749', 'Toà nhà 335 Cầu Giấy',
       'Hẻm 243', '71/3C Chế Lan Viên', 'Ngõ Tức Mạ', '380/ /', '258',
       '193', '200/8 Đường Nguyễn Văn Tăng', '74/',
       'Chung cư 15-17 Ngọc Khánh', '41/19 Đường Số 9', '169/16',
       'Ngõ 63', 'Hẻm 283', 'Hẻm 553', 'Ấp 1', 'Ngõ 141', 'Hẻm 10',
       '183 Nguyễn Lương Bằng', '236', '243/ Đường Tôn Đản', 'Kdc 803',
       '19', 'Phú Xuân 2', '59/291', '129-131 Đường Số 2',
       'Dự án Phú Cường', 'Hẻm 585', 'Hẻm 449 Đường Trường Chinh', '327',
       'Ngõ 84', 'Ngõ 42', '364/ 1A', 'Số nhà 12/8', 'Ngõ 315',
       'KĐT Phú Lương', '99', '426/', 'KP5', 'KĐT Đại Kim', 'Ngõ 164',
       '1122/', '335 Cầu Giấy', 'Phú Hồng Thịnh 9', '86',
       'Ngõ 210 Đường Tân Mai', 'Hẻm 109/', 'Ngõ 209', 'Ngõ 698',
       '35 Đường Bến Lội', 'Tổ 38', 'Ngõ 6',
       '1243/12/7c Đường Lê Văn Lương', '109', 'Hẻm 86', 'Khu 126',
       'Ngõ 34A', '34/13 Đường Số 4', 'Hẻm 661', '526/', 'Hẻm 935',
       'Ngõ 406', '2177', 'Ngách 318', '282/', 'Hẻm 357',
       'Nhà số 33, ngách 57/2', '18/78 Đường Hoàng Như Tiếp', 'Hẻm 39',
       'Hẻm 766//', '19/', 'Hẻm 304/ Hòa Hưng', '40/',
       '131 Đường Tô Hiến Thành', '449', 'Ngõ 1', 'KP3', 'Ngõ 171',
       'Ngõ 204', 'Ngõ Tân Lạc', 'KĐT Lê Hồng Phong II', 'Ngõ 52',
       '49/7G', '25A', '6/3 Ấp Thanh Sơn', 'Số 7/61', 'Số 4 ngõ 44',
       'Ngõ 339', 'Dự án KDC Bình Hưng', 'Ngõ 521 Đường Cổ Nhuế',
       'VSIP 1', 'Hẻm 688', 'Khu dân cư Phú Hồng Thịnh 8',
       'Dự án KDC Hồng Long', 'Hẻm 224', 'Ngõ 105', '212B', '2581', '70',
       'Số nhà 13', '1365', 'Hẻm 194', '527/', 'Hẻm 212', 'Ngõ 639',
       '191', 'Ngõ 5xx', '2279', '403', 'Ngõ 137', 'Ngõ 300',
       '9/13 Đường Tây Thạnh', 'Ngõ Tự Do', '147/', 'Khu phố An Dương',
       '68/12A Đường Đình Thôn',
       'Số nhà 02, hẻm 141/172/43 Đường Giáp Nhị', 'Dự án Nam Hùng Vương',
       'Ngõ 97', 'Khu dân cư Hồng Long', 'Ngõ 80', 'Hẻm 297/27D',
       'Ngõ 445', 'Ngõ 360', '80/ Đường Gò Dầu', '95', 'Ngõ 66', '52',
       'Số 53/42', '230', 'Hẻm 288', 'Lý Thường Kiệt',
       'Khu dân cư Nam Rạch Chiếc', '42 - 2', '322/*', '121//', '341',
       'Hẻm 577 Đường Trần Hưng Đạo', 'Ngõ 10', 'Hẻm 446', 'Ngõ 43',
       'Ngõ 91', '18/', '1979', 'Ngõ 104', 'Hẻm 184', '15/13/1G',
       '1234/24 Đường Huỳnh Tấn Phát', 'Ngõ 168', 'Hẻm 568',
       'Dự án Khu đô thị Vườn Đào', 'Hẻm 67', 'Hẻm 211', '2/4',
       'Hương Lộ 3', 'Ngõ 28', '300', 'Hẻm 122', 'Hẻm 915',
       '12 ngõ 353/40', 'Hẻm 133', 'Số nhà 853',
       'Dự án The Sun City Thuận An', 'Ngõ 140', 'Số nhà 27 ngõ 420',
       'Ngõ 5', 'Tổng cục 5 Tân Triều', 'Ngõ 211', 'ngõ 30 Phố Nghĩa Đô',
       '129 Đường Nguyễn Trãi', 'KĐT Tây Nam Kim Giang',
       'Khu đô thị Bình Hoà', '2637', 'Ngõ 61', 'Ngõ 79', 'Số 8',
       'Hẻm 613 đường 3/2', '13/2 Đường Số 7', 'Ngõ 302', 'Ngõ 169',
       'Hẻm 47', '69', '1806', 'Dự án Nam Cầu Tuyên Sơn-Nam Việt Á',
       '337 Đường Trần Xuân Soạn', 'Hẻm 348', 'Ngõ 580', '6', 'Hẻm 669',
       'Hẻm 28', '240/2', 'Số 4 ngõ 43', 'Hẻm 52', 'Hẻm 89', 'Ngõ 178',
       '75/92 Đường Lý Thánh Tông', 'Xxx/22', 'Ngõ 322', 'Ngõ 206',
       'Ngõ 85'], dtype=object)

In [15]:
with sqlite3.connect('output/real_estate.db') as conn:
    cols = 'property_id, property_url, listing_title, total_price, unit_price, city, district, alley_width, features, latitude, longitude, image_url'
    sql = f"""SELECT {cols}, COUNT(*) 
             FROM onehousing_raw
             GROUP BY {cols}
             HAVING COUNT(*) > 1
             """
    df = pd.read_sql(sql, con=conn)
    print(df.shape)

(869, 13)

In [7]:
with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw = pd.read_sql("SELECT * FROM bds_raw", con=conn)
    oh_raw = pd.read_sql("SELECT * FROM onehousing_raw", con = conn)
    df = pd.read_sql("SELECT * FROM cleaned", con=conn)

print(f'BDS RAW: {bds_raw.shape}')
print(f'OH RAW: {oh_raw.shape}')
print(f'CLEANED RAW: {df.shape}')

BDS RAW: (114251, 12)
OH RAW: (869, 13)
CLEANED RAW: (6911, 32)

# Test newly scraped data

In [2]:
import sqlite3
import pandas as pd
import numpy as np

with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw_old = pd.read_sql("SELECT * FROM bds_raw", con=conn)
    oh_raw_old = pd.read_sql("SELECT * FROM onehousing_raw", con = conn)
    df_old = pd.read_sql("SELECT * FROM cleaned", con=conn)

print(f'BDS RAW: {bds_raw_old.shape}')
print(f'OH RAW: {oh_raw_old.shape}')
print(f'CLEANED RAW: {df_old.shape}')

BDS RAW: (114351, 12)
OH RAW: (969, 13)
CLEANED RAW: (6997, 32)