# Check duplicates

In [16]:
import pandas as pd
import sqlite3
import datetime

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [129]:
with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    onehousing_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)
    cleaned = pd.read_sql('SELECT * FROM cleaned', conn)

In [21]:
print(f'Number of duplicated rows in bds_raw: {bds_raw.duplicated().sum()} / {bds_raw.shape[0]}')
print(f'Number of duplicated rows in onehousing_raw: {onehousing_raw.duplicated().sum()} / {onehousing_raw.shape[0]}')
print(f'Number of duplicated rows in cleaned: {cleaned.duplicated().sum()} / {cleaned.shape[0]}')

Number of duplicated rows in bds_raw: 0 / 124933
Number of duplicated rows in onehousing_raw: 694 / 5178
Number of duplicated rows in cleaned: 4 / 10682

## Onehousing_raw

In [130]:
onehousing_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5178 entries, 0 to 5177
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   property_id           5175 non-null   object
 1   property_url          5178 non-null   object
 2   listing_title         5176 non-null   object
 3   total_price           5174 non-null   object
 4   unit_price            5174 non-null   object
 5   city                  5145 non-null   object
 6   district              5145 non-null   object
 7   alley_width           3813 non-null   object
 8   features              5176 non-null   object
 9   latitude              5176 non-null   float64
 10  longitude             5176 non-null   float64
 11  property_description  4207 non-null   object
 12  image_url             5176 non-null   object
dtypes: float64(2), object(11)
memory usage: 526.0+ KB

### Check NaN

In [135]:
onehousing_raw[onehousing_raw['property_description'].isna()]

,property_id,property_url,listing_title,total_price,unit_price,city,district,alley_width,features,latitude,longitude,property_description,image_url
0,ULHEKO,https://onehousing.vn/bds/Nha-mat-ngo-cach-Pho-Lua-100m--P--Van-Phuc--Q--Ha-Dong--TP--Ha-Noi.ULHEKO,"Nhà mặt ngõ cách Phố Lụa 100m, P. Vạn Phúc, Q. Hà Đông, TP. Hà Nội",9.2 tỷ,271 triệu/m²,TP. Hà Nội,Q. Hà Đông,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Bắc - 7.8m; Số tầng: 5; Diện tích: 33.9 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/355c72a5-37b5-4b62-819a-f1f34e64d071/2c9427839a4a2959019b2c413fa75633_CLONE/LIVING_ROOM/scaled_1000040570_1765975397648.jpg
1,SKUOOI,https://onehousing.vn/bds/Nha-mat-ngo-cach-Xuan-Dinh-50m--P--Xuan-Dinh--Q--Bac-Tu-Liem--TP--Ha-Noi.SKUOOI,"Nhà mặt ngõ cách Xuân Đỉnh 50m, P. Xuân Đỉnh, Q. Bắc Từ Liêm, TP. Hà Nội",17 tỷ,422 triệu/m²,TP. Hà Nội,Q. Bắc Từ Liêm,Độ rộng ngõ\r\n4m - 6m,Hướng mặt tiền: Tây Bắc - 4.1m; Số tầng: 6; Diện tích: 40.3 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/eb81035f-a264-4aed-932c-e524bac4e5e5/2c9427839a4a2959019ba140fe0c7de0_CLONE/LIVING_ROOM/image_picker_0225B86C-1140-496C-9131-6DC827356E26-75883-00001587015572D0_1767937910623.jpg
2,YWGUVT,https://onehousing.vn/bds/Nha-mat-ngo-cach-Kim-Nguu-100m--P--Vinh-Tuy--Q--Hai-Ba-Trung--TP--Ha-Noi.YWGUVT,"Nhà mặt ngõ cách Kim Ngưu 100m, P. Vĩnh Tuy, Q. Hai Bà Trưng, TP. Hà Nội",5.2 tỷ,203 triệu/m²,TP. Hà Nội,Q. Hai Bà Trưng,Độ rộng ngõ\r\n2m - 3m,Hướng mặt tiền: Đông Bắc - 1.2m; Số tầng: 4.5; Diện tích: 25.6 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/62ea34f7-62ce-4f11-92c8-cd8d8c9ca823/2c9427839a4a2959019b30c1bfac58c6_CLONE/LIVING_ROOM/scaled_1000060304_1766050118802.jpg
3,IIWMDZ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Ha-Tri-20m--P--Ha-Cau--Q--Ha-Dong--TP--Ha-Noi.IIWMDZ,"Nhà mặt ngõ cách Hà Trì 20m, P. Hà Cầu, Q. Hà Đông, TP. Hà Nội",18.5 tỷ,242 triệu/m²,TP. Hà Nội,Q. Hà Đông,Độ rộng ngõ\r\n6m - 7m,Hướng mặt tiền: Đông Nam - 5m; Số tầng: 4; Diện tích: 76.5 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/8ebf97a2-39ac-491a-a797-aad2e820c127/2c9427839a4a2959019b48e5eb8d5f0c_CLONE/LIVING_ROOM/scaled_1000060911_1766455083168.jpg
4,NKHHRZ,https://onehousing.vn/bds/Nha-mat-ngo-cach-Thai-Thinh-30m--P--Thinh-Quang--Q--Dong-Da--TP--Ha-Noi.NKHHRZ,"Nhà mặt ngõ cách Thái Thịnh 30m, P. Thịnh Quang, Q. Đống Đa, TP. Hà Nội",19.5 tỷ,548 triệu/m²,TP. Hà Nội,Q. Đống Đa,Độ rộng ngõ\r\n3m - 4m,Hướng mặt tiền: Tây Bắc - 3.4m; Số tầng: 6; Diện tích: 35.6 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/8995d755-c3d8-4b33-9b79-39c28c273d4f/2c9427839a4a2959019ba138a6847ddd_CLONE/LIVING_ROOM/image_picker_2E3A0736-3D43-4694-BD18-B10DAE346EF8-88338-00002DF9C82EA189_1767937353914.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,XZVFLI,https://onehousing.vn/bds/Nha-mat-ngo-cach-An-Duong-Vuong--duong-gom-chan-de--30m--P--Phu-Thuong--Q--Tay-Ho--TP--Ha-Noi.XZVFLI,"Nhà mặt ngõ cách An Dương Vương (đường gom chân đê) 30m, P. Phú Thượng, Q. Tây Hồ, TP. Hà Nội",7.3 tỷ,243 triệu/m²,TP. Hà Nội,Q. Tây Hồ,Độ rộng ngõ\n2m - 3m,Hướng mặt tiền: Đông - 3.37m; Số tầng: 5; Diện tích: 30 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/a9ed56bc-be04-41dd-b4ac-be616ecbef5b/2c94211a9a4a2a77019bc537c83311b0_CLONE/LIVING_ROOM/image_picker_92E6F958-8977-4334-8955-A0ED2616217D-12059-000003F8BE41603C_1768540949790.jpg
967,HEJKTD,https://onehousing.vn/bds/Dat-nen-cach-Thuy-Khue-30m--P--Thuy-Khue--Q--Tay-Ho--TP--Ha-Noi.HEJKTD,"Đất nền cách Thụy Khuê 30m, P. Thụy Khuê, Q. Tây Hồ, TP. Hà Nội",12.5 tỷ,298 triệu/m²,TP. Hà Nội,Q. Tây Hồ,Độ rộng ngõ\n4m - 6m,Hướng mặt tiền: Tây - 5m; Diện tích: 42 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/b8cefe55-d83a-4b16-8157-10d1da022c28/2c9427839a4a2959019bc52d6a970ed4_CLONE/LOCAL_STREET/image_picker_980BAC1D-452B-4E0E-89B6-93D72319DE8A-17715-00003D5AED13AD36_1768539992110.jpg
968,DFWKWE,https://onehousing.vn/bds/Nha-mat-pho-Ho-Dac-Di--P--Nam-Dong--Q--Dong-Da--TP--Ha-Noi.DFWKWE,"Nhà mặt phố Hồ Đắc Di, P. Nam Đồng, Q. Đống Đa, TP. Hà Nội",20 tỷ,523 triệu/m²,TP. Hà Nội,Q. Đống Đa,None,Hướng mặt tiền: Nam - 3.5m; Số tầng: 5; Diện tích: 38.26 m²,21.00101,105.866667,None,https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/cad56689-256f-4cb0-8e25-a5b92ec82f77/2c94211a9a4a2a77019bc50e48851197_CLONE/LOCAL_STREET/image_picker_124CD226-D867-4B9C-B020-650F4B8F7B41-28308-0000035C4C919F0A_1768539659522.jpg
4432,None,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None
5108,None,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None

### Check duplicates

In [24]:
onehousing_raw.duplicated(subset=['property_id', 'property_description', 'listing_title', 'total_price', 'unit_price', 'city', 'district', 'alley_width', 'features']).sum()

np.int64(694)

In [50]:
onehousing_raw[onehousing_raw.duplicated(keep=False)]['property_id'].value_counts()
# Cái này chỉ đếm các giá trị bị lặp và trừ cái giá trị đầu tiên ra cho nên nó mới có đoạn count = 1. Thêm keep=False sẽ loại bỏ trường hợp này

property_id
NUOM18    3
DRRYCF    3
SCIKUF    3
N6LXER    3
P0OH1K    3
         ..
SBYPWV    2
DDR6H5    2
O9PAHW    2
WTJNTL    2
FIQGXM    2
Name: count, Length: 683, dtype: int64

In [53]:
onehousing_raw[onehousing_raw['property_id'] == 'LB4VTG']['alley_width'].duplicated()

644     False
1010    False
Name: alley_width, dtype: bool

In [85]:
onehousing_raw[(onehousing_raw['property_id'].duplicated()) & (onehousing_raw.duplicated() == False)].head()

,property_id,property_url,listing_title,total_price,unit_price,city,district,alley_width,features,latitude,longitude,property_description,image_url
1010,LB4VTG,https://onehousing.vn/bds/Nha-mat-ngo-cach-Au-Co-100m--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.LB4VTG,"Nhà mặt ngõ cách Âu Cơ 100m, P. Nhật Tân, Q. Tây Hồ, TP. Hà Nội",13.5 tỷ,162 triệu/m²,TP. Hà Nội,Q. Tây Hồ,Độ rộng ngõ\n3.1m - 3.9m,Hướng mặt tiền: Đông Nam - 5.3m; Số tầng: 7; Diện tích: 83.2 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Âu Cơ 100m, Q. Tây Hồ, diện tích 83.2m² x 7 tầng Nhà mặt tiền 5.3m, hướng Đông Nam, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 83.2m² với tổng diện tích xây dựng 400m²... Nhà mặt tiền 5.3m, hướng Đông Nam, độ rộng ngõ tiếp giáp 5m, khoảng cách ra trục đường chính 100m... Kết cấu bao gồm: 7 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/39ab8a42-617f-4742-be7f-2059bfe29e87/2c94211a9a4a2a77019b509fc21f67d8_CLONE/LIVING_ROOM/scaled_1000074668_1766584571308.jpg
1021,VK8IVO,https://onehousing.vn/bds/Nha-mat-ngo-cach-Phu-My-50m--P--My-Dinh-2--Q--Nam-Tu-Liem--TP--Ha-Noi.VK8IVO,"Nhà mặt ngõ cách Phú Mỹ 50m, P. Mỹ Đình 2, Q. Nam Từ Liêm, TP. Hà Nội",26 tỷ,371 triệu/m²,TP. Hà Nội,Q. Nam Từ Liêm,Độ rộng ngõ\n3.1m - 3.9m,Hướng mặt tiền: Đông - 4.66m; Số tầng: 7; Diện tích: 70 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Phú Mỹ 50m, Q. Nam Từ Liêm, diện tích 70m² x 7 tầng Nhà mặt tiền 4.66m, hướng Đông, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 70m² với tổng diện tích xây dựng 490m²... Nhà mặt tiền 4.66m, hướng Đông, độ rộng ngõ tiếp giáp 3m, khoảng cách ra trục đường chính 50m... Kết cấu bao gồm: 7 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/915545b2-a36d-406a-b8b7-9b59eb8907f3/2c9427839a4a2959019b5a1489bb6934_CLONE/LIVING_ROOM/image_picker_110454A4-6C77-4400-806D-2429FD12A82C-70572-000025D13C91E7B8_1766743697600.jpg
1046,6JEZ9M,https://onehousing.vn/bds/Nha-mat-ngo-cach-Bach-Mai-200m--P--Bach-Mai--Q--Hai-Ba-Trung--TP--Ha-Noi.6JEZ9M,"Nhà mặt ngõ cách Bạch Mai 200m, P. Bạch Mai, Q. Hai Bà Trưng, TP. Hà Nội",6.9 tỷ,325 triệu/m²,TP. Hà Nội,Q. Hai Bà Trưng,Độ rộng ngõ\n2m - 3m,Hướng mặt tiền: Nam - 3.33m; Số tầng: 5; Diện tích: 21.2 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Bạch Mai 200m, Q. Hai Bà Trưng, diện tích 21.2m² x 5 tầng Nhà mặt tiền 3.33m, hướng Nam, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 21.2m² với tổng diện tích xây dựng 100m²... Nhà mặt tiền 3.33m, hướng Nam, độ rộng ngõ tiếp giáp 2m, khoảng cách ra trục đường chính 200m... Kết cấu bao gồm: 5 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/11c1b8cf-7688-4867-b487-eb4b940f3382/2c9427839a4a2959019bd01c292e1191_CLONE/LIVING_ROOM/scaled_5091_1769255975213.jpg
1047,2EMHLG,https://onehousing.vn/bds/Nha-mat-ngo-cach-Lac-Long-Quan-50m--P--Nghia-Do--Q--Cau-Giay--TP--Ha-Noi.2EMHLG,"Nhà mặt ngõ cách Lạc Long Quân 50m, P. Nghĩa Đô, Q. Cầu Giấy, TP. Hà Nội",10 tỷ,333 triệu/m²,TP. Hà Nội,Q. Cầu Giấy,Độ rộng ngõ\n3.1m - 3.9m,Hướng mặt tiền: Tây Bắc - 3.42m; Số tầng: 5; Diện tích: 30 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Lạc Long Quân 50m, Q. Cầu Giấy, diện tích 30m² x 5 tầng Nhà mặt tiền 3.42m, hướng Tây Bắc, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 30m² với tổng diện tích xây dựng 150m²... Nhà mặt tiền 3.42m, hướng Tây Bắc, độ rộng ngõ tiếp giáp 3.5m, khoảng cách ra trục đường chính 50m... Kết cấu bao gồm: 5 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/2009aed9-9e79-4887-a5f3-87ac325093e4/2c9427839a4a2959019b5501facf669a_CLONE/LIVING_ROOM/image_picker_27679C95-6D43-462F-84A6-310409FAFAC3-34021-000009D49534E424_1766657988093.jpg
1054,OPP5GA,https://onehousing.vn/bds/Nha-mat-ngo-cach-Den-Lu-2-15m--P--Hoang-Van-Thu--Q--Hoang-Mai--TP--Ha-Noi.OPP5GA,"Nhà mặt ngõ cách Đền Lừ 2 15m, P. Hoàng Văn Thụ, Q. Hoàng Mai, TP. Hà Nội",33.5 tỷ,558 triệu/m²,TP. Hà Nội,Q. Hoàng Mai,Độ rộng ngõ\n6.1m - 10m,Hướng mặt tiền: Đông Nam - 4.38m; Số tầng: 7; Diện tích: 60 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Đền Lừ 2 15m, Q. Hoàng Mai, diện tích 60m² x 7 tầng Nhà mặt tiền 4.38m, hướng Đông Nam, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 60m² với tổng diện tích xây dựng 420m²... Nhà mặt tiền 4.38m, hướng Đông Nam, độ rộng ngõ tiếp giáp 12m, khoảng cách ra trục đường chính 15m... Kết cấu bao gồm: 7 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/f0bb84ef-e35e-43f4-8cf9-03e5ce2475cd/2c94211a9a4a2a77019bb600d2170a15_CLONE/LIVING_ROOM/image_picker_37346F50-8CFE-4BA8-B3F0-D9986F7DB9CF-339-0000001D846FCAFE_1768285990485.jpg

In [72]:
oh_raw_copy = onehousing_raw.copy()

null_ind = oh_raw_copy[oh_raw_copy['property_id'].isna()]['property_id'].index
extracted_ids = oh_raw_copy['property_url'].str.split('.').str[-1]
oh_raw_copy['property_id'] = oh_raw_copy['property_id'].fillna(extracted_ids)
oh_raw_copy.iloc[null_ind]

,property_id,property_url,listing_title,total_price,unit_price,city,district,alley_width,features,latitude,longitude,property_description,image_url
4432,YNZR7P,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None
5108,YNZR7P,https://onehousing.vn/bds/Nha-mat-pho-Xuan-Dieu--P--Nhat-Tan--Q--Tay-Ho--TP--Ha-Noi.YNZR7P,None,None,None,None,None,None,None,NaN,NaN,None,None
5160,LXJ7OH,https://onehousing.vn/bds/Nha-mat-ngo-cach-Quoc-Tu-Giam-200m--P--Quoc-Tu-Giam--Q--Dong-Da--TP--Ha-Noi.LXJ7OH,"Nhà mặt ngõ cách Quốc Tử Giám 200m, P. Quốc Tử Giám, Q. Đống Đa, TP. Hà Nội",8.4 tỷ,274 triệu/m²,TP. Hà Nội,Q. Đống Đa,Độ rộng ngõ\n2m - 3m,Hướng mặt tiền: Đông Bắc - 2.41m; Số tầng: 5; Diện tích: 30.7 m²,21.00101,105.866667,"Bán nhà mặt ngõ cách Quốc Tử Giám 200m, Q. Đống Đa, diện tích 30.7m² x 5 tầng Nhà mặt tiền 2.41m, hướng Đông Bắc, sổ đỏ rõ ràng, pháp lý minh bạch, giá tốt. Liên hệ gặp ngay chủ nhà. Nhà có diện tích đất thực tế là 30.7m² với tổng diện tích xây dựng 30.7m²... Nhà mặt tiền 2.41m, hướng Đông Bắc, độ rộng ngõ tiếp giáp 3m, khoảng cách ra trục đường chính 200m... Kết cấu bao gồm: 5 tầng cao ...",https://rs.onehousing.vn/fast/320x0/filters:quality(95):format(webp)/cdn1.onehousing.vn/media/RESIDENTIAL/d28b3d7d-f0c9-4c9b-a54c-e5261175c9c7/2c9427839a4a2959019c0eac56692716_CLONE/LOCAL_STREET/scaled_IMG20260129180635_1769773092015.jpg

In [80]:
oh_raw = onehousing_raw.copy()

extracted_city = oh_raw['listing_title'].str.split(',').str[-1]
extracted_district = oh_raw['listing_title'].str.split(',').str[-2]
oh_raw['new_city'] = oh_raw['city'].fillna(extracted_city)
oh_raw['new_district'] = oh_raw['district'].fillna(extracted_district)

oh_raw[(oh_raw['city'].isna()) | oh_raw['district'].isna()][['new_city', 'new_district', 'city', 'district', 'listing_title']]

,new_city,new_district,city,district,listing_title
1012,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Phúc Lợi 120m, P. Phúc Lợi, Q. Long Biên, TP. Hà Nội"
1013,TP. Hà Nội,Q. Bắc Từ Liêm,None,None,"Nhà mặt ngõ cách Trần Cung 300m, P. Cổ Nhuế 1, Q. Bắc Từ Liêm, TP. Hà Nội"
1020,TP. Hà Nội,Q. Ba Đình,None,None,"Nhà mặt ngõ cách Kim Mã 60m, P. Ngọc Khánh, Q. Ba Đình, TP. Hà Nội"
1023,TP. Hà Nội,Q. Hà Đông,None,None,"Nhà mặt ngõ cách Lê Trọng Tấn 30m, P. Dương Nội, Q. Hà Đông, TP. Hà Nội"
1872,TP. Hà Nội,Q. Nam Từ Liêm,None,None,"Nhà mặt ngõ cách Lương Thế Vinh 60m, P. Trung Văn, Q. Nam Từ Liêm, TP. Hà Nội"
1936,TP. Hà Nội,Q. Thanh Xuân,None,None,"Nhà mặt ngõ cách Bùi Xương Trạch 250m, P. Khương Đình, Q. Thanh Xuân, TP. Hà Nội"
1940,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Bờ Sông Sét 10m, P. Thịnh Liệt, Q. Hoàng Mai, TP. Hà Nội"
2379,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Trịnh Đình Cửu 20m, P. Định Công, Q. Hoàng Mai, TP. Hà Nội"
2791,TP. Hà Nội,Q. Ba Đình,None,None,"Nhà mặt ngõ cách Hoàng Hoa Thám 100m, P. Ngọc Hà, Q. Ba Đình, TP. Hà Nội"
3200,TP. Hà Nội,H. Gia Lâm,None,None,"Nhà mặt ngõ cách Đường Bát Khối 50m, X. Đông Dư, H. Gia Lâm, TP. Hà Nội"
4041,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Nguyễn Lam 100m, P. Phúc Đồng, Q. Long Biên, TP. Hà Nội"
4051,TP. Hà Nội,Q. Hai Bà Trưng,None,None,"Nhà mặt ngõ cách Đồng Nhân 40m, P. Đồng Nhân, Q. Hai Bà Trưng, TP. Hà Nội"
4055,TP. Hà Nội,Q. Nam Từ Liêm,None,None,"Nhà mặt ngõ cách Nguyễn Đổng Chi 30m, P. Cầu Diễn, Q. Nam Từ Liêm, TP. Hà Nội"
4432,None,None,None,None,None
4433,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Phúc Lợi 120m, P. Phúc Lợi, Q. Long Biên, TP. Hà Nội"
4434,TP. Hà Nội,Q. Bắc Từ Liêm,None,None,"Nhà mặt ngõ cách Trần Cung 300m, P. Cổ Nhuế 1, Q. Bắc Từ Liêm, TP. Hà Nội"
4435,TP. Hà Nội,Q. Ba Đình,None,None,"Nhà mặt ngõ cách Kim Mã 60m, P. Ngọc Khánh, Q. Ba Đình, TP. Hà Nội"
4436,TP. Hà Nội,Q. Hà Đông,None,None,"Nhà mặt ngõ cách Lê Trọng Tấn 30m, P. Dương Nội, Q. Hà Đông, TP. Hà Nội"
4588,TP. Hà Nội,Q. Nam Từ Liêm,None,None,"Nhà mặt ngõ cách Lương Thế Vinh 60m, P. Trung Văn, Q. Nam Từ Liêm, TP. Hà Nội"
4605,TP. Hà Nội,Q. Thanh Xuân,None,None,"Nhà mặt ngõ cách Bùi Xương Trạch 250m, P. Khương Đình, Q. Thanh Xuân, TP. Hà Nội"
4607,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Bờ Sông Sét 10m, P. Thịnh Liệt, Q. Hoàng Mai, TP. Hà Nội"
4678,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Trịnh Đình Cửu 20m, P. Định Công, Q. Hoàng Mai, TP. Hà Nội"
4762,TP. Hà Nội,Q. Ba Đình,None,None,"Nhà mặt ngõ cách Hoàng Hoa Thám 100m, P. Ngọc Hà, Q. Ba Đình, TP. Hà Nội"
4858,TP. Hà Nội,H. Gia Lâm,None,None,"Nhà mặt ngõ cách Đường Bát Khối 50m, X. Đông Dư, H. Gia Lâm, TP. Hà Nội"
5031,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Nguyễn Lam 100m, P. Phúc Đồng, Q. Long Biên, TP. Hà Nội"
5033,TP. Hà Nội,Q. Hai Bà Trưng,None,None,"Nhà mặt ngõ cách Đồng Nhân 40m, P. Đồng Nhân, Q. Hai Bà Trưng, TP. Hà Nội"
5034,TP. Hà Nội,Q. Nam Từ Liêm,None,None,"Nhà mặt ngõ cách Nguyễn Đổng Chi 30m, P. Cầu Diễn, Q. Nam Từ Liêm, TP. Hà Nội"
5108,None,None,None,None,None
5117,TP. Hà Nội,Q. Hà Đông,None,None,"Nhà mặt ngõ cách Đường Đa Sỹ 68m, P. Kiến Hưng, Q. Hà Đông, TP. Hà Nội"
5129,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Ngọc Trì 30m, P. Long Biên, Q. Long Biên, TP. Hà Nội"
5133,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Thịnh Liệt 10m, P. Thịnh Liệt, Q. Hoàng Mai, TP. Hà Nội"
5135,TP. Hà Nội,Q. Long Biên,None,None,"Nhà mặt ngõ cách Ngọc Trì 30m, P. Long Biên, Q. Long Biên, TP. Hà Nội"
5137,TP. Hà Nội,Q. Hoàng Mai,None,None,"Nhà mặt ngõ cách Thịnh Liệt 10m, P. Thịnh Liệt, Q. Hoàng Mai, TP. Hà Nội"

In [94]:
oh_raw_copy = onehousing_raw.copy()

def new_oh_rule(oh_raw):
    # Bỏ các cột mà đến cả property_url với listing_title cũng chẳng có
    oh_raw.dropna(subset=['property_url', 'listing_title'], inplace=True)

    # Thay thế các cột có \r\n thành \n
    for col in ['listing_title', 'city', 'district', 'alley_width', 'features', 'property_description']:
        oh_raw[col] = oh_raw[col].str.replace('\r\n', '\n').str.strip()
    
    # Xử lý các trường hợp property_id bị null
    extracted_ids = oh_raw['property_url'].str.split('.').str[-1]
    oh_raw['property_id'] = oh_raw['property_id'].fillna(extracted_ids)

    # Xử lý các đoạn bị null city, district
    extracted_city = oh_raw['listing_title'].str.split(',').str[-1]
    extracted_district = oh_raw['listing_title'].str.split(',').str[-2]
    oh_raw['city'] = oh_raw['city'].fillna(extracted_city)
    oh_raw['district'] = oh_raw['district'].fillna(extracted_district)

    # Dropna nếu dòng có nhiều giá trị NULL
    oh_raw.dropna(subset=['listing_title', 'total_price', 'city', 'district'], inplace=True)

    # Drop duplicates nếu có
    oh_raw.drop_duplicates(inplace=True)

    return oh_raw

oh_raw_copy = new_oh_rule(oh_raw_copy)

In [87]:
oh_raw_copy.duplicated().sum()

np.int64(0)

## Batdongsan_raw

In [136]:
bds_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124933 entries, 0 to 124932
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             124933 non-null  object
 1   url            124933 non-null  object
 2   title          124933 non-null  object
 3   short_address  124933 non-null  object
 4   address_parts  124933 non-null  object
 5   latitude       124933 non-null  float64
 6   longitude      124933 non-null  float64
 7   main_info      124933 non-null  object
 8   description    124933 non-null  object
 9   other_info     124933 non-null  object
 10  image_urls     124933 non-null  object
dtypes: float64(2), object(9)
memory usage: 10.5+ MB

## Cleaned

In [97]:
cleaned[cleaned['Web'] == "Onehousing"][['Đơn giá xây dựng', 'Chất lượng còn lại']]

      Đơn giá xây dựng  Chất lượng còn lại
6451         8221171.0                0.85
6452         8221171.0                0.85
6453         8221171.0                0.85
6454         8221171.0                0.85
6455         8221171.0                0.85
...                ...                 ...
8785         8221171.0                0.85
8786         8221171.0                0.85
8787         8221171.0                0.85
8788               NaN                 NaN
8789         8221171.0                0.85

[982 rows x 2 columns]

In [106]:
print(cleaned.iloc[8788][['Chất lượng còn lại', 'Đơn giá xây dựng']])
print(pd.isna(cleaned.iloc[8788]['Chất lượng còn lại']))
print(pd.isna(cleaned.iloc[8788]['Đơn giá xây dựng']))

Chất lượng còn lại    NaN
Đơn giá xây dựng      NaN
Name: 8788, dtype: object
True
True

In [128]:
cleaned[cleaned['Yếu tố khác'].isna()]['Web'].value_counts()

Web
Onehousing    982
Batdongsan      2
Name: count, dtype: int64

In [119]:
cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10682 entries, 0 to 10681
Data columns (total 32 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Tỉnh/Thành phố                        10682 non-null  object
 1   Thành phố/Quận/Huyện/Thị xã           10682 non-null  object
 2   Xã/Phường/Thị trấn                    10682 non-null  object
 3   Đường phố                             10682 non-null  object
 4   Chi tiết                              10682 non-null  object
 5   Nguồn thông tin                       10682 non-null  object
 6   Tình trạng giao dịch                  10682 non-null  object
 7   Thời điểm giao dịch/rao bán           10682 non-null  object
 8   Thông tin liên hệ                     0 non-null      object
 9   Giá rao bán/giao dịch                 10682 non-null  float64
 10  Giá ước tính                          10682 non-null  int64
 11  Loại đơn giá (đ/m2 hoặc đ/m ngang)    10682 non-null  object
 12  Đơn giá đất                           9700 non-null   float64
 13  Lợi thế kinh doanh                    9700 non-null   object
 14  Số tầng công trình                    10682 non-null  float64
 15  Tổng diện tích sàn                    10682 non-null  float64
 16  Đơn giá xây dựng                      10674 non-null  float64
 17  Năm xây dựng                          0 non-null      object
 18  Chất lượng còn lại                    10674 non-null  float64
 19  Diện tích đất (m2)                    10682 non-null  float64
 20  Kích thước mặt tiền (m)               10682 non-null  float64
 21  Kích thước chiều dài (m)              10682 non-null  float64
 22  Số mặt tiền tiếp giáp                 10682 non-null  int64
 23  Hình dạng                             10682 non-null  object
 24  Độ rộng ngõ/ngách nhỏ nhất (m)        10682 non-null  float64
 25  Khoảng cách tới trục đường chính (m)  10682 non-null  float64
 26  Mục đích sử dụng đất                  10682 non-null  object
 27  Yếu tố khác                           9698 non-null   object
 28  Tọa độ (vĩ độ)                        10682 non-null  float64
 29  Tọa độ (kinh độ)                      10682 non-null  float64
 30  Hình ảnh của bài đăng                 10682 non-null  object
 31  Web                                   10682 non-null  object
dtypes: float64(13), int64(2), object(17)
memory usage: 2.6+ MB

# Chạy lại database

In [ ]:
import sqlite3
import pandas as pd
from commons.config import *
from main import clean

# Xuất raw data từ db cũ ra
with sqlite3.connect('output/real_estate.db') as conn:
    bds_raw = pd.read_sql('SELECT * FROM bds_raw', conn)
    oh_raw = pd.read_sql('SELECT * FROM onehousing_raw', conn)

# Xuất raw data ra file csv
bds_raw.to_csv(DETAILS_CSV_PATH['Batdongsan'], encoding='utf-8-sig')
oh_raw.to_csv(DETAILS_CSV_PATH['Onehousing'], encoding='utf-8-sig')

Xong xóa cho bạn cái db (làm thế này để m ko bỏ lỡ)

# Chạy lại add clean đồ
clean()

# Test auto scrape

In [1]:
from seleniumbase import SB

with SB(uc=True, headed=True) as sb:
    sb.open("https://batdongsan.com.vn")

    # Click the "Đăng nhập" button
    sb.wait_for_element_visible("#kct_login", timeout=10)
    sb.click("#kct_login")

    # Wait for the login iframe to appear
    sb.wait_for_element_visible(
        'iframe[src="https://batdongsan.com.vn/sellernet/internal-sign-in"]',
        timeout=10
    )

    # Switch into the iframe
    sb.switch_to_frame(
        'iframe[src="https://batdongsan.com.vn/sellernet/internal-sign-in"]'
    )

    # Wait for the username input inside iframe
    sb.wait_for_element_visible('input[name="username"]', timeout=15)

    # Click + type (extra safe for React-based inputs)
    sb.click('input[name="username"]')
    sb.type('input[name="username"]', '0328765904')

    sb.click('input[name="password]')
    sb.type('input[name="password]', 'Vyatran123')

    sb.click("#signin-button")

    sb.sleep(5)

NoSuchElementException: Message:
 Element {input[name="password]} was not present after 7 seconds!